### ISSUE TITLE
Fails to mount multi-device fs [c38b7167aa]

### ISSUE THREAD

**Issue by RAOF** [koverstreet/bcachefs#395]
Version c38b7167aa5f3b

`bcachefs show-super`:
```
External UUID:                  a4b165a2-556b-4650-88b8-d90f8ee4b473
Internal UUID:                  7eefb620-ddab-4859-9449-9ca659257331
Device index:                   4
Label:                          
Version:                        inode_v2
Oldest version on disk:         854472355
Created:                        Tue Nov  2 17:56:16 2021
Sequence number:                176
Superblock size:                66632
Clean:                          0
Devices:                        6
Sections:                       journal,members,crypt,replicas_v0,disk_groups,clean,journal_seq_blacklist
Features:                       lz4,journal_seq_blacklist_v3,reflink,new_siphash,inline_data,new_extent_overwrite,incompressible,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,reflink_inline_data,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                alloc_info,alloc_metadata,extents_above_btree_updates_done,bformat_overflow_done

Options:
  block_size:                   4k
  btree_node_size:              256k
  errors:                       continue [ro] panic 
  metadata_replicas:            2
  data_replicas:                2
  metadata_replicas_required:   1
  data_replicas_required:       1
  encoded_extent_max:           64k
  metadata_checksum:            none [crc32c] crc64 xxhash 
  data_checksum:                none [crc32c] crc64 xxhash 
  compression:                  none [lz4] gzip zstd 
  background_compression:       [none] lz4 gzip zstd 
  str_hash:                     crc32c crc64 [siphash] 
  metadata_target:              ssd
  foreground_target:            ssd
  background_target:            rotational
  promote_target:               ssd
  erasure_code:                 0
  inodes_32bit:                 1
  shard_inode_numbers:          1
  inodes_use_key_cache:         1
  gc_reserve_percent:           8
  gc_reserve_bytes:             0
  root_reserve_percent:         0
  wide_macs:                    0
  acl:                          1
  usrquota:                     0
  grpquota:                     0
  prjquota:                     0
  journal_flush_delay:          1000
  journal_flush_disabled:       0
  journal_reclaim_delay:        1000
  journal_transaction_names:    0

members (size 344):
  Device:                       0
    UUID:                       8f6bbc2d-3b2b-4423-ad13-1a50108279e0
    Size:                       2.7T
    Bucket size:                512k
    First bucket:               0
    Buckets:                    5722222
    Last mount:                 Thu Mar 24 17:44:25 2022
    State:                      rw
    Group:                      rotational (0)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       1
    UUID:                       93b4098e-bba5-4577-8576-c2cd25086a6d
    Size:                       2.7T
    Bucket size:                512k
    First bucket:               0
    Buckets:                    5722222
    Last mount:                 Thu Mar 24 17:44:25 2022
    State:                      rw
    Group:                      rotational (0)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       2
    UUID:                       67701b0f-e143-4d48-8280-12dd5999b168
    Size:                       3.6T
    Bucket size:                512k
    First bucket:               0
    Buckets:                    7630895
    Last mount:                 Thu Mar 24 17:44:25 2022
    State:                      rw
    Group:                      rotational (0)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       3
    UUID:                       f7129d1d-25a9-4de4-9d16-e9fbd03d0629
    Size:                       3.6T
    Bucket size:                512k
    First bucket:               0
    Buckets:                    7630895
    Last mount:                 Thu Mar 24 17:44:25 2022
    State:                      rw
    Group:                      rotational (0)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       4
    UUID:                       1f0dfbdb-b149-4cc9-9b3e-f3624bee4b43
    Size:                       238G
    Bucket size:                256k
    First bucket:               0
    Buckets:                    976793
    Last mount:                 Thu Mar 24 17:44:25 2022
    State:                      rw
    Group:                      ssd (1)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    1
    Freespace initialized:      1
  Device:                       5
    UUID:                       0ceeb0bd-0b50-4b96-ab96-305c8380b3e9
    Size:                       238G
    Bucket size:                512k
    First bucket:               0
    Buckets:                    488396
    Last mount:                 Thu Mar 24 17:44:25 2022
    State:                      rw
    Group:                      ssd (1)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    1
    Freespace initialized:      1
```

dmesg of attempted mount:
```
[ 6062.493300] bcachefs: bch2_fs_open() 
[ 6062.493317] bcachefs: bch2_read_super() 
[ 6062.494727] bcachefs: bch2_read_super() ret 0
[ 6062.494735] bcachefs: bch2_read_super() 
[ 6062.539590] bcachefs: bch2_read_super() ret 0
[ 6062.539633] bcachefs: bch2_read_super() 
[ 6062.585544] bcachefs: bch2_read_super() ret 0
[ 6062.585586] bcachefs: bch2_read_super() 
[ 6062.624247] bcachefs: bch2_read_super() ret 0
[ 6062.624289] bcachefs: bch2_read_super() 
[ 6063.353934] bcachefs: bch2_read_super() ret 0
[ 6063.353944] bcachefs: bch2_read_super() 
[ 6064.097953] bcachefs: bch2_read_super() ret 0
[ 6064.097963] bcachefs: bch2_fs_alloc() 
[ 6064.115241] bcachefs: bch2_fs_journal_init() 
[ 6064.115497] bcachefs: bch2_fs_journal_init() ret 0
[ 6064.115962] bcachefs: bch2_fs_btree_cache_init() 
[ 6064.118387] bcachefs: bch2_fs_btree_cache_init() ret 0
[ 6064.121418] bcachefs: bch2_fs_encryption_init() 
[ 6064.121486] bcachefs: bch2_fs_encryption_init() ret 0
[ 6064.121492] bcachefs: __bch2_fs_compress_init() 
[ 6064.121581] bcachefs: __bch2_fs_compress_init() ret 0
[ 6064.122458] bcachefs: bch2_fs_fsio_init() 
[ 6064.125677] bcachefs: bch2_fs_fsio_init() ret 0
[ 6064.125680] bcachefs: bch2_dev_alloc() 
[ 6064.127359] bcachefs: bch2_dev_alloc() ret 0
[ 6064.127364] bcachefs: bch2_dev_alloc() 
[ 6064.128581] bcachefs: bch2_dev_alloc() ret 0
[ 6064.128586] bcachefs: bch2_dev_alloc() 
[ 6064.129933] bcachefs: bch2_dev_alloc() ret 0
[ 6064.129936] bcachefs: bch2_dev_alloc() 
[ 6064.131241] bcachefs: bch2_dev_alloc() ret 0
[ 6064.131245] bcachefs: bch2_dev_alloc() 
[ 6064.131682] bcachefs: bch2_dev_alloc() ret 0
[ 6064.131684] bcachefs: bch2_dev_alloc() 
[ 6064.132246] bcachefs: bch2_dev_alloc() ret 0
[ 6064.138965] bcachefs: bch2_fs_alloc() ret 0
[ 6064.141105] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): recovering from unclean shutdown
[ 6064.141130] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): starting journal read
[ 6065.561510] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): journal read done on device nvme1n1, ret 0
[ 6066.421629] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): journal read done on device nvme0n1, ret 0
[ 6122.627930] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): journal read done on device sda2, ret 0
[ 6123.237511] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): journal read done on device sdb2, ret 0
[ 6131.103274] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): journal read done on device sdc, ret 0
[ 6131.103902] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): journal read done on device sdd, ret 0
[ 6138.232471] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): journal read done, 18484317 keys in 1780 entries, seq 9128266
[ 6138.232478] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): dropped unflushed entries 9128256-9128265
[ 6154.191730] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): starting alloc read
[ 6167.767608] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): alloc read done
[ 6167.767613] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): starting stripes_read
[ 6167.767620] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): stripes_read done
[ 6167.767623] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): starting journal replay, 9303896 keys
[ 6172.282827] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): going read-write
[ 6213.437450] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): journal replay done
[ 6213.437458] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): reading snapshots table
[ 6213.437491] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): reading snapshots done
[ 6213.437493] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): checking for deleted inodes
[ 6215.412926] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): pointer to nonexistent lru 5:15810754936
[ 6215.412939] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): inconsistency detected - emergency read only
[ 6215.412943] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): error in fsck: error -5 while deleting inode
[ 6215.495855] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): Error in recovery: error in recovery (-5)
[ 6215.495868] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): IO error
[ 6215.495876] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): shutting down
[ 6215.495899] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): flushing journal and stopping allocators
[ 6215.495903] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): flushing journal and stopping allocators complete
[ 6215.565712] bcachefs (a4b165a2-556b-4650-88b8-d90f8ee4b473): shutdown complete
[ 6216.115764] bcachefs: bch2_fs_open() ret -5
```

**Comment by RAOF** [comment]
Backtrace of lru failure, taken from bachefs-tools:
```
#0  lru_delete (time=15810754936, idx=83660, id=5, trans=0x7fffffffdc10) at libbcachefs/lru.c:50
#1  bch2_lru_change (trans=trans@entry=0x7fffffffdc10, id=5, idx=83660, old_time=old_time@entry=15810754936, 
    new_time=new_time@entry=0x7fffffffd460) at libbcachefs/lru.c:119
#2  0x000055555560e5f2 in bch2_trans_mark_alloc (trans=0x7fffffffdc10, old=..., new=0x5555614e06d8, flags=<optimized out>)
    at libbcachefs/alloc_background.c:482
#3  0x00005555555d69ee in bch2_trans_mark_key (flags=<optimized out>, new=<optimized out>, old=..., trans=0x7fffffffdc10)
    at libbcachefs/bkey_methods.h:83
#4  run_one_trans_trigger (overwrite=false, i=0x5555614df140, trans=0x7fffffffdc10) at libbcachefs/btree_update_leaf.c:495
#5  run_btree_triggers (trans=trans@entry=0x7fffffffdc10, btree_id=btree_id@entry=BTREE_ID_alloc, btree_id_start=0x5555614df050)
    at libbcachefs/btree_update_leaf.c:529
#6  0x00005555555d7675 in bch2_trans_commit_run_triggers (trans=<optimized out>) at libbcachefs/btree_update_leaf.c:571
#7  __bch2_trans_commit (trans=trans@entry=0x7fffffffdc10) at libbcachefs/btree_update_leaf.c:1097
#8  0x00005555555daf2e in bch2_trans_commit (flags=4, journal_seq=0x0, disk_res=0x7fffffffd6c0, trans=0x7fffffffdc10)
    at libbcachefs/btree_update.h:102
#9  bch2_btree_delete_range_trans (trans=trans@entry=0x7fffffffdc10, id=id@entry=BTREE_ID_extents, start=..., end=..., 
    update_flags=update_flags@entry=4, journal_seq=journal_seq@entry=0x0) at libbcachefs/btree_update_leaf.c:1711
#10 0x000055555557a229 in fsck_inode_rm (snapshot=4294967295, inum=4434, trans=<optimized out>) at libbcachefs/fsck.c:239
#11 check_inode (full=true, prev=<synthetic pointer>, iter=0x7fffffffdb10, trans=0x7fffffffdc10) at libbcachefs/fsck.c:868
#12 check_inodes (c=c@entry=0x7ffff7a9b000, full=full@entry=true) at libbcachefs/fsck.c:961
#13 0x000055555557d4dd in bch2_fsck_full (c=c@entry=0x7ffff7a9b000) at libbcachefs/fsck.c:2383
#14 0x0000555555597242 in bch2_fs_recovery (c=<optimized out>) at libbcachefs/recovery.c:1248
#15 0x0000555555584d8d in bch2_fs_start (c=c@entry=0x7ffff7a9b000) at libbcachefs/super.c:897
#16 0x00005555555872df in bch2_fs_open (devices=devices@entry=0x7fffffffe5a8, nr_devices=nr_devices@entry=6, opts=...)
    at libbcachefs/super.c:1905
#17 0x00005555556165e5 in cmd_fsck (argc=6, argc@entry=8, argv=0x7fffffffe5a8, argv@entry=0x7fffffffe598) at cmd_fsck.c:90
#18 0x000055555555edd6 in main (argc=<optimized out>, argv=0x7fffffffe598) at bcachefs.c:197
```

**Comment by YellowOnion** [comment]
@koverstreet I think you had a patch for this in the works? conversion/update code not working or something?

**Comment by YellowOnion** [comment]
@RAOF this is working now right? Can I close the issue.

**Comment by RAOF** [comment]
Yup! It was a partially upgraded filesystem. The upgrade path has been fixed, this now works.
