### ISSUE TITLE
bcachefs fsck failed [bad0c8c50758b4447d529f61017c1a8c85976a3e] (bcachefs-tools)

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#434]
The same failed as kernel   "mount -o fsck,fix_errors" . The filesystem contain about 5 snapshots

```
gdb -ex run --args /stow/opt/bcachefs-tools/sbin/bcachefs fsck /dev/sdb9 -y
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /stow/opt/bcachefs-tools/sbin/bcachefs...
Starting program: /stow/opt/bcachefs-tools/sbin/bcachefs fsck /dev/sdb9 -y
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0x7ffff7ff4600 (LWP 18622)]
[New Thread 0x7ffff7feb600 (LWP 18623)]
[New Thread 0x7ffff7fd5600 (LWP 18624)]
[New Thread 0x7ffff7fcc600 (LWP 18625)]
[New Thread 0x7ffff7fc3600 (LWP 18626)]
[New Thread 0x7ffff7fb5600 (LWP 18627)]
[New Thread 0x7ffff7fac600 (LWP 18628)]
[New Thread 0x7ffff7f61600 (LWP 18629)]
[New Thread 0x7ffff7f58600 (LWP 18630)]
[New Thread 0x7ffff7f4f600 (LWP 18631)]
[New Thread 0x7ffff7f46600 (LWP 18632)]
[New Thread 0x7ffff7e07600 (LWP 18633)]
recovering from clean shutdown, journal seq 476566
journal read done, 0 keys in 1 entries, seq 476567
[New Thread 0x7ffff4cbf600 (LWP 18634)]
[New Thread 0x7fffeffff600 (LWP 18635)]
checking allocations



checking need_discard and freespace btrees
starting journal replay, 0 keys
checking lrus
checking backpointers to alloc keys
checking backpointers to extents
checking extents to backpointers
checking alloc to lru refs
starting fsck
bcachefs: libbcachefs/fsck.c:500: key_visible_in_snapshot: Assertion `!(id > ancestor)' failed.

Thread 1 "bcachefs" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff5892256 in __GI_abort () at abort.c:79
#2  0x00007ffff589214f in __assert_fail_base (
    fmt=0x7ffff59f0ef0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x4ede82 "!(id > ancestor)", file=0x4ede53 "libbcachefs/fsck.c", 
    line=500, function=<optimized out>) at assert.c:92
#3  0x00007ffff58a08e2 in __GI___assert_fail (
    assertion=assertion@entry=0x4ede82 "!(id > ancestor)", 
    file=file@entry=0x4ede53 "libbcachefs/fsck.c", line=line@entry=500, 
    function=function@entry=0x4ee210 <__PRETTY_FUNCTION__.12> "key_visible_in_snapshot") at assert.c:101
#4  0x00000000004573c0 in key_visible_in_snapshot (c=c@entry=0x7ffff7f63000, 
    seen=seen@entry=0x7fffffffe060, id=<optimized out>, 
    ancestor=<optimized out>) at libbcachefs/fsck.c:500
#5  0x00000000004582ba in check_extent_start (iter=0x7fffffffe090, k=..., 
    extent_ends=0x7fffffffdfb0, s=0x7fffffffe060, trans=0x7fffffffe130)
    at libbcachefs/fsck.c:1152
#6  check_extent (extent_ends=0x7fffffffdfb0, s=0x7fffffffe060, 
    inode=0x7fffffffdfd0, iter=0x7fffffffe090, trans=0x7fffffffe130)
    at libbcachefs/fsck.c:1273
#7  check_extents (c=c@entry=0x7ffff7f63000) at libbcachefs/fsck.c:1320
#8  0x000000000045cb4d in bch2_fsck_full (c=c@entry=0x7ffff7f63000)
    at libbcachefs/fsck.c:2401
--Type <RET> for more, q to quit, c to continue without paging--c
#9  0x0000000000434851 in bch2_fs_recovery (c=<optimized out>) at libbcachefs/recovery.c:1354
#10 0x00000000004235dc in bch2_fs_start (c=c@entry=0x7ffff7f63000) at libbcachefs/super.c:900
#11 0x0000000000426095 in bch2_fs_open (devices=devices@entry=0x7fffffffeb18, nr_devices=<optimized out>, nr_devices@entry=1, opts=...) at libbcachefs/super.c:1909
#12 0x00000000004c0450 in cmd_fsck (argc=1, argc@entry=3, argv=0x7fffffffeb18, argv@entry=0x7fffffffeb08) at cmd_fsck.c:90
#13 0x000000000040517c in main (argc=<optimized out>, argv=0x7fffffffeb08) at bcachefs.c:198
(gdb) 
(gdb) 
```

**Comment by koverstreet** [comment]
I've been seeing this intermittently, it's fairly high on my todo list

**Comment by bhzhu203** [comment]
bcachefs-tools version cc1f2deb960478d556e2d61be70ca412e12425d1
```
Starting program: /stow/opt/bcachefs-tools/sbin/bcachefs fsck /dev/sdb9 -y
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0x7ffff7ff4600 (LWP 10747)]
[New Thread 0x7ffff7feb600 (LWP 10748)]
[New Thread 0x7ffff7fd5600 (LWP 10749)]
[New Thread 0x7ffff7fcc600 (LWP 10750)]
[New Thread 0x7ffff7fc3600 (LWP 10751)]
[New Thread 0x7ffff7fb5600 (LWP 10752)]
[New Thread 0x7ffff7fac600 (LWP 10753)]
[New Thread 0x7ffff7f61600 (LWP 10754)]
[New Thread 0x7ffff7f58600 (LWP 10755)]
[New Thread 0x7ffff7f4f600 (LWP 10756)]
[New Thread 0x7ffff7f46600 (LWP 10757)]
[New Thread 0x7ffff7e07600 (LWP 10758)]
recovering from unclean shutdown
journal read done, 0 keys in 1 entries, seq 850029
[New Thread 0x7ffff4cbf600 (LWP 10769)]
[New Thread 0x7fffeffff600 (LWP 10770)]
checking allocations
checking need_discard and freespace btrees
starting journal replay, 0 keys
journal replay done
checking lrus
checking backpointers to alloc keys
checking backpointers to extents
checking extents to backpointers
checking alloc to lru refs
starting fsck
bcachefs: libbcachefs/fsck.c:500: key_visible_in_snapshot: Assertion `!(id > ancestor)' failed.

Thread 1 "bcachefs" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: 没有那个文件或目录.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff5892256 in __GI_abort () at abort.c:79
#2  0x00007ffff589214f in __assert_fail_base (fmt=0x7ffff59f0ef0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x4d2dea "!(id > ancestor)", file=0x4d2dbb "libbcachefs/fsck.c", line=500, function=<optimized out>) at assert.c:92
#3  0x00007ffff58a08e2 in __GI___assert_fail (assertion=assertion@entry=0x4d2dea "!(id > ancestor)", 
    file=file@entry=0x4d2dbb "libbcachefs/fsck.c", line=line@entry=500, 
    function=function@entry=0x4d3170 <__PRETTY_FUNCTION__.12> "key_visible_in_snapshot") at assert.c:101
#4  0x0000000000466fd0 in key_visible_in_snapshot (c=c@entry=0x7ffff7f63000, seen=seen@entry=0x7fffffffe060, id=<optimized out>, 
    ancestor=<optimized out>) at libbcachefs/fsck.c:500
#5  0x0000000000467eca in check_extent_start (iter=0x7fffffffe090, k=..., extent_ends=0x7fffffffdfb0, s=0x7fffffffe060, 
    trans=0x7fffffffe130) at libbcachefs/fsck.c:1152
#6  check_extent (extent_ends=0x7fffffffdfb0, s=0x7fffffffe060, inode=0x7fffffffdfd0, iter=0x7fffffffe090, trans=0x7fffffffe130)
    at libbcachefs/fsck.c:1273
#7  check_extents (c=c@entry=0x7ffff7f63000) at libbcachefs/fsck.c:1320
#8  0x000000000046c75d in bch2_fsck_full (c=c@entry=0x7ffff7f63000) at libbcachefs/fsck.c:2401
#9  0x000000000048da31 in bch2_fs_recovery (c=<optimized out>) at libbcachefs/recovery.c:1354
#10 0x000000000049c32c in bch2_fs_start (c=c@entry=0x7ffff7f63000) at libbcachefs/super.c:900
#11 0x000000000049ede5 in bch2_fs_open (devices=devices@entry=0x7fffffffeb18, nr_devices=<optimized out>, nr_devices@entry=1, opts=...)
    at libbcachefs/super.c:1909
#12 0x00000000004b7550 in cmd_fsck (argc=1, argc@entry=3, argv=0x7fffffffeb18, argv@entry=0x7fffffffeb08) at cmd_fsck.c:90
#13 0x000000000040517c in main (argc=<optimized out>, argv=0x7fffffffeb08) at bcachefs.c:198
```

**Comment by bhzhu203** [comment]
issue solved.
