### ISSUE TITLE
`bcachefs device evacuate` does not work correctly with `background_compression` [bf4ac0284f66]

### ISSUE THREAD

**Issue by asyncth** [koverstreet/bcachefs#448]
**Version**

Kernel bf4ac0284f664cb26efe8b2677563746fd4a1d02
Tools `d2c2c5954c3304598cb2ecc2e8f11788356f5afc`

**Description**
`bcachefs device evacuate` triggers a kernel BUG if `background_compression` is enabled. Could not reproduce when `background_compression` is set to `none`. Interestingly, what exactly happens seems to depend on which device I'm trying to evacuate: evacuating `vdi1` (device 5) hangs the system completely and I was unable to get data from `dmesg` for that type of crash (due to `journalctl -k -b -1` not showing any kind of errors), while evacuating `vdh1` (device 4) does not hang the system, instead `bcachefs` userspace util gets stuck, becomes unkillable and prevents the FS from being unmounted.

**Generic info**
Both ran before trying to evacuate either of those devices.

`bcachefs fs usage`:
```
Filesystem: 07e7ede1-6a1a-4d7a-9811-37adeaad21fa
Size:                    29623698432
Used:                     2196469760
Online reserved:                   0

Data type       Required/total  Devices
btree:          1/3             [vdd1 vdg1 vdi1]             4718592
btree:          1/3             [vdg1 vdh1 vdi1]             3145728
btree:          1/3             [vdd1 vde1 vdg1]              786432
btree:          1/3             [vde1 vdg1 vdi1]             1572864
btree:          1/3             [vdd1 vde1 vdf1]            14155776
btree:          1/3             [vdd1 vde1 vdi1]             1572864
btree:          1/3             [vde1 vdf1 vdg1]             2359296
btree:          1/3             [vdf1 vdg1 vdi1]             3932160
user:           1/3             [vdd1 vdf1 vdg1]            16449536
user:           1/3             [vdg1 vdh1 vdi1]           897810432
user:           1/3             [vde1 vdf1 vdg1]            15714304
user:           1/3             [vdd1 vde1 vdg1]            16867328
user:           1/3             [vdd1 vdg1 vdh1]              196608
user:           1/3             [vdf1 vdg1 vdh1]              393216
user:           1/3             [vdd1 vde1 vdf1]           945623040
user:           1/3             [vdd1 vde1 vdi1]               12288
user:           1/3             [vdd1 vdf1 vdh1]              294912
user:           1/3             [vdd1 vdg1 vdi1]               12288
user:           1/3             [vde1 vdg1 vdi1]              294912
user:           1/3             [vdf1 vdg1 vdi1]               24576
cached:         1/1             [vdg1]                        131072
cached:         1/1             [vde1]                        147456
cached:         1/1             [vdi1]                      16643072
cached:         1/1             [vdd1]                        143360
cached:         1/1             [vdf1]                        102400
cached:         1/1             [vdh1]                      16462848

(no label) (device 0):          vdd1              rw
                                data         buckets    fragmented
  free:                            0           19012
  sb:                        3149824              13        258048
  journal:                  41680896             159
  btree:                     7077888              27
  user:                    326492672            1252       1712128
  cached:                     143360               9
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:               5366611968           20472

(no label) (device 1):          vde1              rw
                                data         buckets    fragmented
  free:                            0           19015
  sb:                        3149824              13        258048
  journal:                  41680896             159
  btree:                     6815744              26
  user:                    326184960            1249       1232896
  cached:                     147456              10
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:               5366611968           20472

(no label) (device 2):          vdf1              rw
                                data         buckets    fragmented
  free:                            0           19018
  sb:                        3149824              13        258048
  journal:                  41680896             159
  btree:                     6815744              26
  user:                    326169088            1249       1249280
  cached:                     102400               7
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:               5366611968           20472

(no label) (device 3):          vdg1              rw
                                data         buckets    fragmented
  free:                            0           19067
  sb:                        3149824              13        258048
  journal:                  41680896             159
  btree:                     5505024              21
  user:                    315896832            1207        512000
  cached:                     131072               5
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:               5366611968           20472

(no label) (device 4):          vdh1              rw
                                data         buckets    fragmented
  free:                            0           19082
  sb:                        3149824              13        258048
  journal:                  41680896             159
  btree:                     1048576               4
  user:                    299565056            1145        589824
  cached:                   16462848              69
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:               5366611968           20472

(no label) (device 5):          vdi1              rw
                                data         buckets    fragmented
  free:                            0           19068
  sb:                        3149824              13        258048
  journal:                  41680896             159
  btree:                     4980736              19
  user:                    299384832            1146       1032192
  cached:                   16643072              67
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:               5366611968           20472
```
`bcachefs show-super`:
```
External UUID:                  07e7ede1-6a1a-4d7a-9811-37adeaad21fa
Internal UUID:                  2b7aaaf2-9fbd-48b6-9851-c28435f8aed7
Device index:                   0
Label:                          data_bcachefs_raid
Version:                        backpointers
Oldest version on disk:         backpointers
Created:                        Sat Aug 27 18:16:16 2022
Sequence number:                201
Superblock size:                5592
Clean:                          0
Devices:                        6
Sections:                       members,replicas_v0,clean,journal_seq_blacklist,journal_v2,counters
Features:                       zstd,journal_seq_blacklist_v3,new_siphash,new_extent_overwrite,incompressible,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                alloc_info,alloc_metadata,extents_above_btree_updates_done,bformat_overflow_done

Options:
  block_size:                   4.00 KiB
  btree_node_size:              256 KiB
  errors:                       continue [ro] panic
  metadata_replicas:            3
  data_replicas:                3
  metadata_replicas_required:   1
  data_replicas_required:       1
  encoded_extent_max:           64.0 KiB
  metadata_checksum:            none [crc32c] crc64 xxhash
  data_checksum:                none [crc32c] crc64 xxhash
  compression:                  none lz4 gzip [zstd]
  background_compression:       none lz4 gzip [zstd]
  str_hash:                     crc32c crc64 [siphash]
  metadata_target:              none
  foreground_target:            none
  background_target:            none
  promote_target:               none
  erasure_code:                 0
  inodes_32bit:                 1
  shard_inode_numbers:          1
  inodes_use_key_cache:         1
  gc_reserve_percent:           8
  gc_reserve_bytes:             0 B
  root_reserve_percent:         0
  wide_macs:                    0
  acl:                          1
  usrquota:                     0
  grpquota:                     0
  prjquota:                     0
  journal_flush_delay:          1000
  journal_flush_disabled:       0
  journal_reclaim_delay:        100

members (size 344):
  Device:                       0
    UUID:                       92113117-b489-4515-bc83-727aab67ae9f
    Size:                       5.00 GiB
    Bucket size:                256 KiB
    First bucket:               0
    Buckets:                    20472
    Last mount:                 Sat Aug 27 18:43:15 2022
    State:                      rw
    Label:                      (none)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       1
    UUID:                       21149ccc-b44b-4d62-acd8-e4aabdd65f6d
    Size:                       5.00 GiB
    Bucket size:                256 KiB
    First bucket:               0
    Buckets:                    20472
    Last mount:                 Sat Aug 27 18:43:15 2022
    State:                      rw
    Label:                      (none)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       2
    UUID:                       46dd6f4e-dfe8-441f-8d08-555db87a98ca
    Size:                       5.00 GiB
    Bucket size:                256 KiB
    First bucket:               0
    Buckets:                    20472
    Last mount:                 Sat Aug 27 18:43:15 2022
    State:                      rw
    Label:                      (none)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       3
    UUID:                       cb693d67-d043-4033-90d9-7f899748860a
    Size:                       5.00 GiB
    Bucket size:                256 KiB
    First bucket:               0
    Buckets:                    20472
    Last mount:                 Sat Aug 27 18:43:15 2022
    State:                      rw
    Label:                      (none)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       4
    UUID:                       bae35c0a-de9e-470a-bdf2-e4c548235d25
    Size:                       5.00 GiB
    Bucket size:                256 KiB
    First bucket:               0
    Buckets:                    20472
    Last mount:                 Sat Aug 27 18:43:15 2022
    State:                      rw
    Label:                      (none)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       5
    UUID:                       79fc16b8-e6e8-4928-9673-b804853c3ac6
    Size:                       5.00 GiB
    Bucket size:                256 KiB
    First bucket:               0
    Buckets:                    20472
    Last mount:                 Sat Aug 27 18:43:15 2022
    State:                      rw
    Label:                      (none)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
```
**Tools bugs**
`perf top -p $(pidof bcachefs)`:
![perf](https://user-images.githubusercontent.com/97792158/187040647-ac8b2428-00c9-45dd-8437-b14b41ec775f.png)

`bt`:
```
(gdb) bt
#0  0x00007ffff7ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007ffff7adce27 in nanosleep () from /lib64/libc.so.6
#2  0x00007ffff7adcd5e in sleep () from /lib64/libc.so.6
#3  0x000000000041309c in bchu_data (fs=..., cmd=...) at libbcachefs.c:518
#4  0x0000000000407c3d in cmd_device_evacuate (argc=<optimized out>, argc@entry=2, 
    argv=<optimized out>, argv@entry=0x7fffffffe398) at cmd_device.c:330
#5  0x00000000004052de in device_cmds (argv=0x7fffffffe398, argc=<optimized out>) at bcachefs.c:132
#6  main (argc=<optimized out>, argv=0x7fffffffe398) at bcachefs.c:188
```

**Kernel bugs**
`dmesg`: [attached](https://github.com/koverstreet/bcachefs/files/9438372/dmesg.txt)

**Comment by koverstreet** [comment]
ancient bug, assuming it's been fixed; reopen if not
