### ISSUE TITLE
Kernel panic: "trans path oveflow" on mount after crash

### ISSUE THREAD

**Issue by BlackLotus** [koverstreet/bcachefs#453]
My kernel is build against 176718966e14c5f832ead8cea2e0e45aba51f5ef

**Generic info**
Provide the output of:
```
bcachefs fs usage (either only works against a mounted fs or fails for me with)
error opening /dev/mapper/cryptolvm-bcachefsRoot: not a bcachefs filesystem

# bcachefs show-super /dev/mapper/cryptolvm-bcachefsRoot 
External UUID:                  d5f2628b-7a3e-4cd9-aab9-e56b6d305b09
Internal UUID:                  ee1c2068-e30d-4ba2-9bb7-85f017ddb4a8
Device index:                   0
Label:                          
Version:                        backpointers
Oldest version on disk:         new_data_types
Created:                        Mon Jun 20 17:28:36 2022
Sequence number:                184
Superblock size:                4224
Clean:                          0
Devices:                        1
Sections:                       members,replicas_v0,clean,journal_seq_blacklist,journal_v2,counters
Features:                       zstd,journal_seq_blacklist_v3,reflink,new_siphash,inline_data,new_extent_overwrite,incompressible,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,reflink_inline_data,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                alloc_info,alloc_metadata,extents_above_btree_updates_done,bformat_overflow_done

Options:
  block_size:                   4.00 KiB
  btree_node_size:              256 KiB
  errors:                       continue [ro] panic
  metadata_replicas:            1
  data_replicas:                1
  metadata_replicas_required:   1
  data_replicas_required:       1
  encoded_extent_max:           64.0 KiB
  metadata_checksum:            none crc32c crc64 [xxhash]
  data_checksum:                none crc32c crc64 [xxhash]
  compression:                  none lz4 gzip [zstd]
  background_compression:       [none] lz4 gzip zstd
  str_hash:                     crc32c crc64 [siphash]
  metadata_target:              none
  foreground_target:            none
  background_target:            none
  promote_target:               none
  erasure_code:                 0
  inodes_32bit:                 1
  shard_inode_numbers:          1
  inodes_use_key_cache:         1
  gc_reserve_percent:           8
  gc_reserve_bytes:             0 B
  root_reserve_percent:         0
  wide_macs:                    0
  acl:                          1
  usrquota:                     0
  grpquota:                     0
  prjquota:                     0
  journal_flush_delay:          1000
  journal_flush_disabled:       0
  journal_reclaim_delay:        100

members (size 64):
  Device:                       0
    UUID:                       84385931-3fec-48c1-b136-5be815eff95e
    Size:                       75.0 GiB
    Bucket size:                256 KiB
    First bucket:               0
    Buckets:                    307200
    Last mount:                 Tue Sep  6 21:51:05 2022
    State:                      rw
    Label:                      (none)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user
    Discard:                    0
    Freespace initialized:      1
```
Since the same error is reproducible in the tools as in the kernel I thought it would be easier to provide the tools output, but when compiling the tools without stripping them I'm triggering a segfault on `fsck`. Here is the output of `bcachefs fsck -n` before I compiled it against master
```
recovering from unclean shutdown
journal read done, 11 keys in 1 entries, seq 740128
checking allocations
checking need_discard and freespace btrees
starting journal replay, 9 keys
going read-write
journal replay done
checking lrus
checking backpointers to alloc keys
checking backpointers to extents
checking extents to backpointers
checking alloc to lru refs
starting fsck
path: idx 20 ref 0:0     btree=extents l=0 pos 1610700500:1672:U32_MAX locks 1
path: idx 14 ref 0:0     btree=extents l=0 pos 1610700500:1704:U32_MAX locks 1
path: idx 22 ref 0:0     btree=extents l=0 pos 1610700500:1832:U32_MAX locks 1
path: idx 23 ref 0:0     btree=extents l=0 pos 1610700500:1960:U32_MAX locks 1
path: idx 24 ref 0:0     btree=extents l=0 pos 1610700500:2040:U32_MAX locks 1
path: idx 25 ref 0:0     btree=extents l=0 pos 1610700500:2168:U32_MAX locks 1
path: idx 26 ref 0:0     btree=extents l=0 pos 1610700500:2296:U32_MAX locks 1
path: idx 27 ref 0:0     btree=extents l=0 pos 1610700500:2424:U32_MAX locks 1
path: idx 28 ref 0:0     btree=extents l=0 pos 1610700500:2552:U32_MAX locks 1
path: idx 30 ref 0:0     btree=extents l=0 pos 1610700500:2680:U32_MAX locks 1
path: idx 31 ref 0:0     btree=extents l=0 pos 1610700500:2808:U32_MAX locks 1
path: idx 32 ref 0:0     btree=extents l=0 pos 1610700500:2864:U32_MAX locks 1
path: idx 33 ref 0:0     btree=extents l=0 pos 1610700500:2872:U32_MAX locks 1
path: idx 34 ref 0:0     btree=extents l=0 pos 1610700500:3000:U32_MAX locks 1
path: idx 35 ref 0:0     btree=extents l=0 pos 1610700500:3128:U32_MAX locks 1
path: idx 37 ref 0:0     btree=extents l=0 pos 1610700500:3256:U32_MAX locks 1
path: idx 39 ref 0:0     btree=extents l=0 pos 1610700500:3384:U32_MAX locks 1
path: idx 40 ref 0:0     btree=extents l=0 pos 1610700500:3512:U32_MAX locks 1
path: idx 41 ref 0:0     btree=extents l=0 pos 1610700500:3640:U32_MAX locks 1
path: idx 42 ref 0:0     btree=extents l=0 pos 1610700500:3768:U32_MAX locks 1
path: idx 43 ref 0:0     btree=extents l=0 pos 1610700500:3800:U32_MAX locks 1
path: idx 44 ref 0:0     btree=extents l=0 pos 1610700500:3928:U32_MAX locks 1
path: idx 46 ref 0:0     btree=extents l=0 pos 1610700500:4056:U32_MAX locks 1
path: idx 48 ref 0:0     btree=extents l=0 pos 1610700500:4080:U32_MAX locks 1
path: idx 49 ref 0:0     btree=extents l=0 pos 1610700500:4208:U32_MAX locks 1
path: idx 50 ref 0:0     btree=extents l=0 pos 1610700500:4336:U32_MAX locks 1
path: idx 51 ref 0:0     btree=extents l=0 pos 1610700500:4464:U32_MAX locks 1
path: idx 52 ref 0:0     btree=extents l=0 pos 1610700500:4592:U32_MAX locks 1
path: idx 53 ref 0:0 P S btree=extents l=0 pos 1610700500:4680:U32_MAX locks 1
path: idx 47 ref 0:0 P S btree=extents l=0 pos 1610700500:4688:U32_MAX locks 1
path: idx 55 ref 0:0 P S btree=extents l=0 pos 1610700500:4816:U32_MAX locks 1
path: idx 56 ref 0:0 P S btree=extents l=0 pos 1610700500:4944:U32_MAX locks 1
path: idx 57 ref 0:0 P S btree=extents l=0 pos 1610700500:5072:U32_MAX locks 1
path: idx 58 ref 0:0 P S btree=extents l=0 pos 1610700500:5200:U32_MAX locks 1
path: idx 59 ref 0:0 P S btree=extents l=0 pos 1610700500:5328:U32_MAX locks 1
path: idx 60 ref 0:0 P S btree=extents l=0 pos 1610700500:5456:U32_MAX locks 1
path: idx  1 ref 0:0 P S btree=extents l=0 pos 1610700500:5584:U32_MAX locks 2
path: idx  4 ref 0:0 P S btree=extents l=0 pos 1610700500:5592:U32_MAX locks 2
path: idx  5 ref 0:0 P S btree=extents l=0 pos 1610700500:5720:U32_MAX locks 2
path: idx  6 ref 0:0 P S btree=extents l=0 pos 1610700500:5848:U32_MAX locks 2
path: idx  7 ref 0:0 P S btree=extents l=0 pos 1610700500:5976:U32_MAX locks 2
path: idx  8 ref 0:0 P S btree=extents l=0 pos 1610700500:6104:U32_MAX locks 2
path: idx  9 ref 0:0 P S btree=extents l=0 pos 1610700500:6120:U32_MAX locks 2
path: idx  2 ref 1:1   S btree=extents l=0 pos 1610700500:6121:U32_MAX locks 2
path: idx 13 ref 1:1 P S btree=extents l=0 pos 1610700500:6248:U32_MAX locks 2
path: idx 16 ref 1:1 P S btree=extents l=0 pos 1610700500:6376:U32_MAX locks 2
path: idx 17 ref 1:1 P S btree=extents l=0 pos 1610700500:6504:U32_MAX locks 2
path: idx 18 ref 1:1 P S btree=extents l=0 pos 1610700500:6560:U32_MAX locks 2
path: idx 19 ref 1:1 P S btree=extents l=0 pos 1610700500:6568:U32_MAX locks 2
path: idx 62 ref 1:1 P S btree=extents l=0 pos 1610700500:6696:U32_MAX locks 2
path: idx 63 ref 1:1 P S btree=extents l=0 pos 1610700500:6824:U32_MAX locks 2
path: idx 15 ref 1:1   S btree=extents l=0 pos 1610700500:6825:U32_MAX locks 2
path: idx  0 ref 1:0     btree=inodes l=0 pos 0:1610700500:U32_MAX locks 1
path: idx 11 ref 0:0     btree=alloc l=0 pos 0:153721:0 locks 1
path: idx 21 ref 0:0     btree=alloc l=0 pos 0:153722:0 locks 1
path: idx 29 ref 0:0     btree=alloc l=0 pos 0:153723:0 locks 1
path: idx 38 ref 0:0 P S btree=alloc l=0 pos 0:153724:0 locks 1
path: idx 54 ref 0:0 P S btree=alloc l=0 pos 0:153725:0 locks 2
path: idx  3 ref 0:0 P S btree=alloc l=0 pos 0:153726:0 locks 2
path: idx 12 ref 0:0     btree=need_discard l=0 pos 0:153721:0 locks 1
path: idx 36 ref 0:0     btree=need_discard l=0 pos 0:153722:0 locks 1
path: idx 45 ref 0:0     btree=need_discard l=0 pos 0:153723:0 locks 1
path: idx 61 ref 0:0 P S btree=need_discard l=0 pos 0:153724:0 locks 1
path: idx 10 ref 0:0 P S btree=need_discard l=0 pos 0:153725:0 locks 2
transaction updates for check_inodes journal seq 740138
  update: btree=extents cached=0 0x1ce61b572e6S
    old u64s 8 type extent 1610700500:6248:U32_MAX len 128 ver 0: crc: c_size 64 size 128 offset 0 nonce 0 csum xxhash compress zstd ptr: 0:153726:272 gen 6
    new u64s 5 type deleted 1610700500:6248:U32_MAX len 0 ver 0
  update: btree=extents cached=0 0x1ce61b572e6S
    old u64s 8 type extent 1610700500:6376:U32_MAX len 128 ver 0: crc: c_size 64 size 128 offset 0 nonce 0 csum xxhash compress zstd ptr: 0:153726:336 gen 6
    new u64s 5 type deleted 1610700500:6376:U32_MAX len 0 ver 0
  update: btree=extents cached=0 0x1ce61b572e6S
    old u64s 8 type extent 1610700500:6504:U32_MAX len 128 ver 0: crc: c_size 72 size 128 offset 0 nonce 0 csum xxhash compress zstd ptr: 0:153726:400 gen 6
    new u64s 5 type deleted 1610700500:6504:U32_MAX len 0 ver 0
  update: btree=extents cached=0 0x1ce61b572e6S
    old u64s 8 type extent 1610700500:6560:U32_MAX len 56 ver 0: crc: c_size 32 size 56 offset 0 nonce 0 csum xxhash compress zstd ptr: 0:153726:472 gen 6
    new u64s 5 type deleted 1610700500:6560:U32_MAX len 0 ver 0
  update: btree=extents cached=0 0x1ce61b572e6S
    old u64s 8 type extent 1610700500:6568:U32_MAX len 8 ver 0: crc: c_size 8 size 8 offset 0 nonce 0 csum xxhash compress incompressible ptr: 0:153726:504 gen 6
    new u64s 5 type deleted 1610700500:6568:U32_MAX len 0 ver 0
  update: btree=extents cached=0 0x1ce61b572e6S
    old u64s 8 type extent 1610700500:6696:U32_MAX len 128 ver 0: crc: c_size 72 size 128 offset 0 nonce 0 csum xxhash compress zstd ptr: 0:153727:0 gen 6
    new u64s 5 type deleted 1610700500:6696:U32_MAX len 0 ver 0
  update: btree=extents cached=0 0x1ce61b572e6S
    old u64s 8 type extent 1610700500:6824:U32_MAX len 128 ver 0: crc: c_size 64 size 128 offset 0 nonce 0 csum xxhash compress zstd ptr: 0:153727:72 gen 6
    new u64s 5 type deleted 1610700500:6824:U32_MAX len 0 ver 0

trans path oveflow
bcachefs: libbcachefs/btree_iter.c:1507: btree_path_alloc: Assertion `0' failed.
```
Here is what I get now with `gdb -ex run --args ./bcachefs fsck -n /dev/mapper/cryptolvm-bcachefsRoot`

```
Starting program: /home/thomas/work/bcachefs-tools/bcachefs fsck -n /dev/mapper/cryptolvm-bcachefsRoot
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff7fc1680 (LWP 42748)]
[New Thread 0x7ffff7fb8680 (LWP 42749)]
[New Thread 0x7ffff7faf680 (LWP 42750)]
[New Thread 0x7ffff7adb680 (LWP 42751)]
[New Thread 0x7ffff7ad2680 (LWP 42752)]
[New Thread 0x7ffff7ac4680 (LWP 42753)]
[New Thread 0x7ffff7abb680 (LWP 42754)]
[New Thread 0x7ffff7a70680 (LWP 42755)]
[New Thread 0x7ffff7a67680 (LWP 42756)]
[New Thread 0x7ffff7a5e680 (LWP 42757)]
[New Thread 0x7ffff7a55680 (LWP 42758)]

Thread 1 "bcachefs" received signal SIGSEGV, Segmentation fault.
0x0000000100020a75 in bch2_btree_cache_scan (shrink=0x7ffff7a73050, sc=<optimized out>) at libbcachefs/btree_cache.c:379
379		trace_and_count(c, btree_cache_scan, sc->nr_to_scan, can_free, ret);
(gdb) bt
#0  0x0000000100020a75 in bch2_btree_cache_scan (shrink=0x7ffff7a73050, sc=<optimized out>) at libbcachefs/btree_cache.c:379
#1  0x00000001000b9534 in run_shrinkers (gfp_mask=1, allocation_failed=<optimized out>) at linux/shrinker.c:121
#2  0x00000001000b1c88 in kmalloc (size=576, flags=1) at include/linux/slab.h:27
#3  0x00000001000b1da9 in bucket_table_alloc (nbuckets=64, gfp=0, ht=0x7ffff7a752c8) at linux/rhashtable.c:182
#4  0x00000001000b2459 in rhashtable_init (ht=ht@entry=0x7ffff7a752c8, params=params@entry=0x10012c3c0 <bch2_btree_key_cache_params>) at linux/rhashtable.c:1057
#5  0x000000010004117f in bch2_fs_btree_key_cache_init (c=c@entry=0x7ffff7a752a0) at libbcachefs/btree_key_cache.c:910
#6  0x00000001000ab9ce in bch2_fs_alloc (opts=..., sb=<optimized out>) at libbcachefs/super.c:793
#7  bch2_fs_open (devices=devices@entry=0x7fffffffeb98, nr_devices=<optimized out>, nr_devices@entry=1, opts=...) at libbcachefs/super.c:1886
#8  0x00000001000c6900 in cmd_fsck (argc=1, argc@entry=3, argv=0x7fffffffeb98, argv@entry=0x7fffffffeb88) at cmd_fsck.c:90
#9  0x000000010000b1b8 in main (argc=<optimized out>, argv=0x7fffffffeb88) at bcachefs.c:198
```

Will provide the kernel output later.

**Comment by BlackLotus** [comment]
Ok d01f633041c50452f9e837b7cc0223e6f37d42da introduced the bug in bcachefs-tools that lead to the segfault (should I open a new bug report for this?)

Using d2c2c5954c3304598cb2ecc2e8f11788356f5afc seems to work? Letting it run without -n worked and I now can mount my root volume again.

Now even d01f633041c50452f9e837b7cc0223e6f37d42da runs without any segfaults. I'm not sure what happened here, but if it mounts I'm fine with it. Canceling the compile of the kernel with debug flags.
