### ISSUE TITLE
snapshot should not point to subvol:  [1ae0d7c505e3

### ISSUE THREAD

**Issue by marcin-github** [koverstreet/bcachefs#468]
After upgrade/rebase to 6.0 I can't mount fs with snapshot:
```
[ 7943.169821] bcachefs (dm-2): shutting down
[ 7943.171177] bcachefs (dm-2): shutdown complete
[ 7949.088968] bcachefs: bch2_fs_open()
[ 7949.089963] bcachefs: bch2_read_super()
[ 7949.101863] bcachefs: bch2_read_super() ret 0
[ 7949.102847] bcachefs: bch2_fs_alloc()
[ 7949.253634] bcachefs: bch2_fs_journal_init()
[ 7949.254632] bcachefs: bch2_fs_journal_init() ret 0
[ 7949.255586] bcachefs: bch2_fs_btree_cache_init()
[ 7949.256669] bcachefs: bch2_fs_btree_cache_init() ret 0
[ 7949.272061] bcachefs: bch2_fs_encryption_init()
[ 7949.273015] bcachefs: bch2_fs_encryption_init() ret 0
[ 7949.273938] bcachefs: __bch2_fs_compress_init()
[ 7949.274867] bcachefs: __bch2_fs_compress_init() ret 0
[ 7949.275775] bcachefs: bch2_fs_fsio_init()
[ 7949.276690] bcachefs: bch2_fs_fsio_init() ret 0
[ 7949.277579] bcachefs: bch2_dev_alloc()
[ 7949.278536] bcachefs: bch2_dev_alloc() ret 0
[ 7949.280207] bcachefs: bch2_fs_alloc() ret 0
[ 7949.281133] bcachefs (dm-2): recovering from unclean shutdown
[ 7949.282034] bcachefs (dm-2): starting journal read
[ 7977.524668] bcachefs (dm-2): journal read done on device dm-2, ret 0
[ 7977.525798] bcachefs (dm-2): journal read done, 0 keys in 1 entries, seq 1483696
[ 7977.691459] bcachefs (dm-2): starting alloc read
[ 7983.572981] bcachefs (dm-2): alloc read done
[ 7983.589384] bcachefs (dm-2): starting stripes_read
[ 7983.590252] bcachefs (dm-2): stripes_read done
[ 7983.591097] bcachefs (dm-2): starting journal replay, 0 keys
[ 7983.591953] bcachefs (dm-2): journal replay done
[ 7983.592796] bcachefs (dm-2): reading snapshots table
[ 7983.593667] bcachefs (dm-2): reading snapshots done
[ 7983.594530] bcachefs (dm-2): checking for deleted inodes
[ 7983.595408] bcachefs (dm-2): inconsistency detected - emergency read only
[ 7983.596283] snapshot should not point to subvol:
[ 7983.596285]   u64s 8 type snapshot 0:4294967295:0 len 0 ver 0: is_subvol 0 deleted 0 parent          0 children 4294967294 4294967293 subvol 1, shutting down
[ 7983.598052] bcachefs (dm-2): error -2104 checking snapshots
[ 7983.599026] bcachefs (dm-2): Error in recovery: error in recovery (fsck_errors_not_fixed)
[ 7983.600870] bcachefs (dm-2): error starting filesystem: fsck_errors_not_fixed
[ 7983.601825] bcachefs (dm-2): shutting down
[ 7983.603028] bcachefs (dm-2): shutdown complete
[ 7983.629417] bcachefs: bch2_fs_open() ret -22
```

bcache fsck stalls while fscking, no i/o activity, strace shows that fsck stuck in `FUTEX_WAIT_PRIVATE`

```
# bcachefs fsck -nvvv /dev/dm-2
bch2_fs_open()
bch2_read_super()
bch2_read_super() ret 0
bch2_fs_alloc()
bch2_fs_journal_init()
bch2_fs_journal_init() ret 0
bch2_fs_btree_cache_init()
bch2_fs_btree_cache_init() ret 0
bch2_fs_encryption_init()
bch2_fs_encryption_init() ret 0
__bch2_fs_compress_init()
__bch2_fs_compress_init() ret 0
bch2_dev_alloc()
bch2_dev_alloc() ret 0
bch2_fs_alloc() ret 0
recovering from unclean shutdown
starting journal read
journal read done on device /dev/dm-2, ret 0
journal read done, 0 keys in 1 entries, seq 1483696
starting alloc read
alloc read done
starting stripes_read
stripes_read done
checking allocations
done checking allocations
checking need_discard and freespace btrees
done checking need_discard and freespace btrees
starting journal replay, 0 keys
journal replay done
checking lrus
done checking lrus
checking backpointers to alloc keys
```

**Comment by bhzhu203** [comment]
maybe you could upgrade your bcachefs-tool version

**Comment by koverstreet** [comment]
Run it under gdb and get a backtrace when it's stuck

**Comment by marcin-github** [comment]
Here you are:
```
(gdb) bt
#0  futex_wait (private=0, expected=2, futex_word=0x7f8d2a10bfd8) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x7f8d2a10bfd8, private=0) at lowlevellock.c:49
#2  0x00007f8d2a21f6e2 in lll_mutex_lock_optimized (mutex=0x7f8d2a10bfd8) at pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=mutex@entry=0x7f8d2a10bfd8) at pthread_mutex_lock.c:93
#4  0x000055ee4103dacb in bch2_btree_cache_scan (shrink=0x7f8d2a10c050, sc=<optimized out>) at libbcachefs/btree_cache.c:295
#5  0x000055ee40f8d0ae in run_shrinkers (gfp_mask=gfp_mask@entry=1, allocation_failed=allocation_failed@entry=false) at linux/shrinker.c:121
#6  0x000055ee4103bf0b in kmalloc (size=size@entry=512, flags=flags@entry=1) at include/linux/slab.h:27
#7  0x000055ee4103d5d6 in __btree_node_mem_alloc (c=c@entry=0x7f8d2a10b000, gfp=gfp@entry=0) at libbcachefs/btree_cache.c:115
#8  0x000055ee4103e708 in bch2_btree_node_mem_alloc (c=c@entry=0x7f8d2a10b000, pcpu_read_locks=pcpu_read_locks@entry=true) at libbcachefs/btree_cache.c:591
#9  0x000055ee40fefc85 in bch2_btree_root_read (c=c@entry=0x7f8d2a10b000, id=id@entry=BTREE_ID_extents, k=k@entry=0x7f8d2a10b7f8, level=1) at libbcachefs/btree_io.c:1575
#10 0x000055ee4101121c in read_btree_roots (c=c@entry=0x7f8d2a10b000) at libbcachefs/recovery.c:958
#11 0x000055ee410130cc in bch2_fs_recovery (c=c@entry=0x7f8d2a10b000) at libbcachefs/recovery.c:1208
#12 0x000055ee40fe3621 in bch2_fs_start (c=0x7f8d2a10b000) at libbcachefs/super.c:899
#13 0x000055ee40fe514b in bch2_fs_open (devices=devices@entry=0x7ffcbe8e9398, nr_devices=nr_devices@entry=1, opts=...) at libbcachefs/super.c:1895
#14 0x000055ee40f81ee7 in cmd_fsck (argc=1, argc@entry=3, argv=0x7ffcbe8e9398, argv@entry=0x7ffcbe8e9388) at cmd_fsck.c:90
#15 0x000055ee40f7730b in main (argc=<optimized out>, argv=0x7ffcbe8e9388) at bcachefs.c:198
(gdb)

```

```
(gdb) bt full
#0  futex_wait (private=0, expected=2, futex_word=0x7f8d2a10bfd8) at ../sysdeps/nptl/futex-internal.h:146
        __ret = -512
        err = <optimized out>
        err = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#1  __GI___lll_lock_wait (futex=futex@entry=0x7f8d2a10bfd8, private=0) at lowlevellock.c:49
No locals.
#2  0x00007f8d2a21f6e2 in lll_mutex_lock_optimized (mutex=0x7f8d2a10bfd8) at pthread_mutex_lock.c:48
        __futex = 0x7f8d2a10bfd8
        private = <optimized out>
        private = <optimized out>
        __value = <optimized out>
        __futex = <optimized out>
#3  ___pthread_mutex_lock (mutex=mutex@entry=0x7f8d2a10bfd8) at pthread_mutex_lock.c:93
        type = <optimized out>
        __PRETTY_FUNCTION__ = "___pthread_mutex_lock"
        id = <optimized out>
#4  0x000055ee4103dacb in bch2_btree_cache_scan (shrink=0x7f8d2a10c050, sc=<optimized out>) at libbcachefs/btree_cache.c:295
        c = 0x7f8d2a10b000
        bc = 0x7f8d2a10bf18
        b = <optimized out>
        t = <optimized out>
        nr = 891288
        can_free = 0
        freed = 0
        touched = 0
        i = <optimized out>
        flags = <optimized out>
        ret = 18446744073709551615
        trigger_writes = true
#5  0x000055ee40f8d0ae in run_shrinkers (gfp_mask=gfp_mask@entry=1, allocation_failed=allocation_failed@entry=false) at linux/shrinker.c:121
        sc = {gfp_mask = 1, nr_to_scan = 891288}
        shrinker = 0x7f8d2a10c050
        info = {uptime = 0, loads = {0, 0, 0}, totalram = 16574193664, freeram = 492830720, sharedram = 0, bufferram = 0, totalswap = 0, freeswap = 0, procs = 0, pad = 0, totalhigh = 0, freehigh = 0, mem_unit = 0}
        want_shrink = 3650717696
#6  0x000055ee4103bf0b in kmalloc (size=size@entry=512, flags=flags@entry=1) at include/linux/slab.h:27
        i = 0
        p = 0x0
#7  0x000055ee4103d5d6 in __btree_node_mem_alloc (c=c@entry=0x7f8d2a10b000, gfp=gfp@entry=0) at libbcachefs/btree_cache.c:115
        b = <optimized out>
#8  0x000055ee4103e708 in bch2_btree_node_mem_alloc (c=c@entry=0x7f8d2a10b000, pcpu_read_locks=pcpu_read_locks@entry=true) at libbcachefs/btree_cache.c:591
        bc = 0x7f8d2a10bf18
        freed = 0x7f8d2a10c020
        b = 0x7f8d2a10be30
        b2 = <optimized out>
        start_time = 896848380386
        flags = 0
        __PRETTY_FUNCTION__ = "bch2_btree_node_mem_alloc"
#9  0x000055ee40fefc85 in bch2_btree_root_read (c=c@entry=0x7f8d2a10b000, id=id@entry=BTREE_ID_extents, k=k@entry=0x7f8d2a10b7f8, level=1) at libbcachefs/btree_io.c:1575
        cl = {{{wq = 0x0, s = 0x0, list = {next = 0x0}, fn = 0x0}, work = {data = {counter = 0}, entry = {next = 0x0, prev = 0x0}, func = 0x0}}, parent = 0x0, remaining = {counter = 1073741825}}
        b = <optimized out>
        ret = 0
        __PRETTY_FUNCTION__ = "bch2_btree_root_read"
#10 0x000055ee4101121c in read_btree_roots (c=c@entry=0x7f8d2a10b000) at libbcachefs/recovery.c:958
        r = 0x7f8d2a10b7f0
        i = 0
        ret = <optimized out>
#11 0x000055ee410130cc in bch2_fs_recovery (c=c@entry=0x7f8d2a10b000) at libbcachefs/recovery.c:1208
        err = 0x55ee4108ef27 "cannot allocate memory"
        clean = 0x0
        last_journal_entry = <optimized out>
        blacklist_seq = 1483696
        journal_seq = 1483704
        write_sb = false
        ret = 0
        __func__ = "bch2_fs_recovery"
#12 0x000055ee40fe3621 in bch2_fs_start (c=0x7f8d2a10b000) at libbcachefs/super.c:899
        mi = 0x55ee42c912f0
        ca = 0x0
        now = 1665431680
        i = 1
--Type <RET> for more, q to quit, c to continue without paging--
        ret = -22
        __PRETTY_FUNCTION__ = "bch2_fs_start"
#13 0x000055ee40fe514b in bch2_fs_open (devices=devices@entry=0x7ffcbe8e9398, nr_devices=nr_devices@entry=1, opts=...) at libbcachefs/super.c:1895
        sb = 0x55ee42c7f240
        c = 0x7f8d2a10b000
        mi = 0x55ee42c802f0
        i = 1
        best_sb = <optimized out>
        err = 0x55ee41088d3e "insufficient devices"
        errbuf = {buf = 0x0, size = 0, pos = 0, last_newline = 0, last_field = 0, indent = 0, atomic = 0 '\000', allocation_failure = false, heap_allocated = true, si_units = PRINTBUF_UNITS_2, human_readable_units = false, has_indent_or_tabstops = false,
          suppress_indent_tabstop_handling = false, nr_tabstops = 0 '\000', cur_tabstop = 0 '\000', _tabstops = "\000\000\000"}
        ret = <optimized out>
        __func__ = "bch2_fs_open"
#14 0x000055ee40f81ee7 in cmd_fsck (argc=1, argc@entry=3, argv=0x7ffcbe8e9398, argv@entry=0x7ffcbe8e9388) at cmd_fsck.c:90
        longopts = {{name = 0x55ee4107d915 "reconstruct_alloc", has_arg = 0, flag = 0x0, val = 82}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        opts = {block_size_defined = 0, btree_node_size_defined = 0, errors_defined = 0, metadata_replicas_defined = 0, data_replicas_defined = 0, metadata_replicas_required_defined = 0, data_replicas_required_defined = 0, encoded_extent_max_defined = 0,
          metadata_checksum_defined = 0, data_checksum_defined = 0, compression_defined = 0, background_compression_defined = 0, str_hash_defined = 0, metadata_target_defined = 0, foreground_target_defined = 0, background_target_defined = 0, promote_target_defined = 0,
          erasure_code_defined = 0, inodes_32bit_defined = 0, shard_inode_numbers_defined = 0, inodes_use_key_cache_defined = 0, btree_node_mem_ptr_optimization_defined = 0, gc_reserve_percent_defined = 0, gc_reserve_bytes_defined = 0, root_reserve_percent_defined = 0,
          wide_macs_defined = 0, inline_data_defined = 0, acl_defined = 0, usrquota_defined = 0, grpquota_defined = 0, prjquota_defined = 0, degraded_defined = 1, very_degraded_defined = 0, discard_defined = 0, verbose_defined = 1, journal_flush_delay_defined = 0,
          journal_flush_disabled_defined = 0, journal_reclaim_delay_defined = 0, move_bytes_in_flight_defined = 0, fsck_defined = 1, fix_errors_defined = 1, ratelimit_errors_defined = 0, nochanges_defined = 1, norecovery_defined = 0, keep_journal_defined = 0,
          read_entire_journal_defined = 0, read_journal_only_defined = 0, noexcl_defined = 0, direct_io_defined = 0, sb_defined = 0, read_only_defined = 0, nostart_defined = 0, reconstruct_alloc_defined = 0, version_upgrade_defined = 0, buckets_nouse_defined = 0, project_defined = 0,
          fs_size_defined = 0, bucket_defined = 0, durability_defined = 0, block_size = 0, btree_node_size = 0, errors = 0 '\000', metadata_replicas = 0 '\000', data_replicas = 0 '\000', metadata_replicas_required = 0 '\000', data_replicas_required = 0 '\000', encoded_extent_max = 0,
          metadata_checksum = 0 '\000', data_checksum = 0 '\000', compression = 0 '\000', background_compression = 0 '\000', str_hash = 0 '\000', metadata_target = 0, foreground_target = 0, background_target = 0, promote_target = 0, erasure_code = 0, inodes_32bit = 0 '\000',
          shard_inode_numbers = 0 '\000', inodes_use_key_cache = 0 '\000', btree_node_mem_ptr_optimization = 0 '\000', gc_reserve_percent = 0 '\000', gc_reserve_bytes = 0, root_reserve_percent = 0 '\000', wide_macs = 0 '\000', inline_data = 0 '\000', acl = 0 '\000',
          usrquota = 0 '\000', grpquota = 0 '\000', prjquota = 0 '\000', degraded = 1 '\001', very_degraded = 0 '\000', discard = 0 '\000', verbose = 1 '\001', journal_flush_delay = 0, journal_flush_disabled = 0 '\000', journal_reclaim_delay = 0, move_bytes_in_flight = 0,
          fsck = 1 '\001', fix_errors = 2 '\002', ratelimit_errors = 0 '\000', nochanges = 1 '\001', norecovery = 0 '\000', keep_journal = 0 '\000', read_entire_journal = 0 '\000', read_journal_only = 0 '\000', noexcl = 0 '\000', direct_io = 0 '\000', sb = 0, read_only = 0 '\000',
          nostart = 0 '\000', reconstruct_alloc = 0 '\000', version_upgrade = 0 '\000', buckets_nouse = 0 '\000', project = 0 '\000', fs_size = 0, bucket = 0, durability = 0 '\000'}
        i = 1
        opt = <optimized out>
        ret = 0
        c = <optimized out>
#15 0x000055ee40f7730b in main (argc=<optimized out>, argv=0x7ffcbe8e9388) at bcachefs.c:198
        cmd = 0x7ffcbe8ea452 "fsck"
```

bcachefs tool version v0.1-564-g72add882+

**Comment by koverstreet** [comment]
I just pushed a fix for the fsck deadlock - can you let me know if it works?

**Comment by koverstreet** [comment]
So per IRC discussion, repair now works. Do you know how to reproduce the original issue?

**Comment by marcin-github** [comment]
Last time the fs was mounted was about 2 months ago. After upgrade kernel to 6.x I couldn't mount it. I don't know the way to reproduce bug.
