### ISSUE TITLE
out of bounds write in __bch2_alloc_to_v4_mut via bkey_reassemble [7889026bc459]

### ISSUE THREAD

**Issue by collinmay** [koverstreet/bcachefs#530]
**Version**

Kernel built from 7889026bc459.

**Generic info**
```
$ bcachefs show-super /dev/nvme0n1p2
External UUID:                              c024f72c-166a-4c45-b40e-7b5fa086c30d
Internal UUID:                              99b25584-5653-4050-8586-493cfaac9820
Device index:                               0
Label:                                      
Version:                                    no_bps_in_alloc_keys
Oldest version on disk:                     new_data_types
Created:                                    Fri Apr 29 20:34:21 2022
Sequence number:                            342
Superblock size:                            5528
Clean:                                      0
Devices:                                    4
Sections:                                   members,replicas_v0,disk_groups,clean,journal_seq_blacklist,journal_v2,counters
Features:                                   journal_seq_blacklist_v3,reflink,new_siphash,inline_data,new_extent_overwrite,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,reflink_inline_data,new_varint,journal_no_flush,alloc_v2,extents_s
Compat features:                            alloc_info,alloc_metadata,extents_above_btree_updates_done,bformat_overflow_done

Options:
  block_size:                               4.00 KiB
  btree_node_size:                          256 KiB
  errors:                                   continue [ro] panic 
  metadata_replicas:                        2
  data_replicas:                            2
  metadata_replicas_required:               2
  data_replicas_required:                   1
  encoded_extent_max:                       64.0 KiB
  metadata_checksum:                        none [crc32c] crc64 xxhash 
  data_checksum:                            none [crc32c] crc64 xxhash 
  compression:                              [none] lz4 gzip zstd 
  background_compression:                   [none] lz4 gzip zstd 
  str_hash:                                 crc32c crc64 [siphash] 
  metadata_target:                          fast
  foreground_target:                        fast
  background_target:                        slow
  promote_target:                           fast
  erasure_code:                             0
  inodes_32bit:                             1
  shard_inode_numbers:                      1
  inodes_use_key_cache:                     1
  gc_reserve_percent:                       8
  gc_reserve_bytes:                         0 B
  root_reserve_percent:                     0
  wide_macs:                                0
  acl:                                      1
  usrquota:                                 0
  grpquota:                                 0
  prjquota:                                 0
  journal_flush_delay:                      1000
  journal_flush_disabled:                   0
  journal_reclaim_delay:                    100
  journal_transaction_names:                1
  nocow:                                    0

members (size 232):
  Device:                                   0
    UUID:                                   1cd63924-7efb-4ff3-9d7a-5e024527c3e9
    Size:                                   1.82 TiB
    Bucket size:                            512 KiB
    First bucket:                           0
    Buckets:                                3813408
    Last mount:                             Tue Apr 11 17:23:13 2023
    State:                                  rw
    Label:                                  fast (0)
    Data allowed:                           journal,btree,user
    Has data:                               journal,btree,user,cached
    Discard:                                0
    Freespace initialized:                  1
  Device:                                   1
    UUID:                                   2c349a07-15da-44bb-9e79-083636677f20
    Size:                                   1.93 TiB
    Bucket size:                            512 KiB
    First bucket:                           0
    Buckets:                                4042797
    Last mount:                             Tue Apr 11 17:23:13 2023
    State:                                  rw
    Label:                                  slow (1)
    Data allowed:                           journal,btree,user
    Has data:                               journal,btree,user,cached
    Discard:                                0
    Freespace initialized:                  1
  Device:                                   2
    UUID:                                   68b453b3-ec39-4981-b7e1-57a416e24028
    Size:                                   1.33 TiB
    Bucket size:                            512 KiB
    First bucket:                           0
    Buckets:                                2790458
    Last mount:                             Tue Apr 11 17:23:13 2023
    State:                                  rw
    Label:                                  slow (1)
    Data allowed:                           journal,btree,user
    Has data:                               journal,btree,user,cached
    Discard:                                0
    Freespace initialized:                  1
  Device:                                   3
    UUID:                                   344d9090-a3cb-4ba1-af18-d403d08ab9a9
    Size:                                   2.73 TiB
    Bucket size:                            512 KiB
    First bucket:                           0
    Buckets:                                5723174
    Last mount:                             Tue Apr 11 17:23:13 2023
    State:                                  rw
    Label:                                  slow (1)
    Data allowed:                           journal,btree,user
    Has data:                               journal,btree,user,cached
    Discard:                                0
    Freespace initialized:                  1
```

**Kernel bug**
This bug always appears shortly after the first write to my filesystem after I mount it. This filesystem was just upgraded from a version of bcachefs from several months ago. The backtraces don't always look the same, but always seem to come from `__bch2_alloc_to_v4_mut`'s call to `bkey_reassemble`.

Here's a backtrace I caught under gdb:
```
(gdb) bt
#0  kasan_report (addr=18446612684310835456, size=size@entry=8, is_write=is_write@entry=true, ip=18446744072639559352) at mm/kasan/report.c:494
#1  0xffffffff815398d0 in check_region_inline (ret_ip=<optimized out>, write=true, size=8, addr=18446612684310835456) at mm/kasan/generic.c:183
#2  0xffffffffc03936b8 in memcpy_u64s_small (u64s=<optimized out>, src=<optimized out>, dst=<optimized out>) at fs/bcachefs/util.h:604
#3  bkey_reassemble (src=..., dst=0xffff8880858ff028) at fs/bcachefs/bkey.h:543
#4  __bch2_alloc_to_v4_mut (trans=trans@entry=0xffff8881003b7b20, k=...) at fs/bcachefs/alloc_background.c:489
#5  0xffffffffc03955cd in bch2_alloc_to_v4_mut_inlined (k=..., trans=0xffff8881003b7b20) at fs/bcachefs/alloc_background.c:527
#6  bch2_trans_start_alloc_update (trans=trans@entry=0xffff8881003b7b20, iter=iter@entry=0xffff8881003b6fe0, pos=...) at fs/bcachefs/alloc_background.c:552
#7  0xffffffffc041ef7b in bch2_trans_mark_pointer (trans=trans@entry=0xffff8881003b7b20, btree_id=btree_id@entry=BTREE_ID_extents, level=level@entry=0, k=..., p=..., flags=flags@entry=65) at fs/bcachefs/buckets.c:1420
#8  0xffffffffc042683d in bch2_trans_mark_extent (trans=<optimized out>, btree_id=<optimized out>, level=<optimized out>, old=..., new=<optimized out>, flags=<optimized out>) at fs/bcachefs/buckets.c:1520
#9  0xffffffffc0411fb4 in bch2_trans_mark_key (flags=<optimized out>, new=<optimized out>, old=..., level=<optimized out>, btree_id=<optimized out>, trans=<optimized out>) at fs/bcachefs/bkey_methods.h:131
#10 bch2_trans_mark_new (flags=<optimized out>, new=<optimized out>, level=<optimized out>, btree_id=<optimized out>, trans=<optimized out>) at fs/bcachefs/bkey_methods.h:157
#11 run_one_trans_trigger (overwrite=<optimized out>, i=0xffff88806c652200, trans=0xffff8881003b7b20) at fs/bcachefs/btree_update_leaf.c:490
#12 run_btree_triggers (trans=trans@entry=0xffff8881003b7b20, btree_id=btree_id@entry=BTREE_ID_extents, btree_id_start=btree_id_start@entry=0xffff88806c652200) at fs/bcachefs/btree_update_leaf.c:518
#13 0xffffffffc0414a2c in bch2_trans_commit_run_triggers (trans=0xffff8881003b7b20) at fs/bcachefs/btree_update_leaf.c:551
#14 __bch2_trans_commit (trans=trans@entry=0xffff8881003b7b20, flags=flags@entry=12) at fs/bcachefs/btree_update_leaf.c:1104
#15 0xffffffffc043da2e in bch2_trans_commit (flags=12, journal_seq=0x0 <fixed_percpu_data>, disk_res=<optimized out>, trans=<optimized out>) at fs/bcachefs/btree_update.h:118
#16 __bch2_data_update_index_update (trans=trans@entry=0xffff8881003b7b20, op=op@entry=0xffff888100f19290) at fs/bcachefs/data_update.c:337
#17 0xffffffffc043deff in bch2_data_update_index_update (op=op@entry=0xffff888100f19290) at fs/bcachefs/data_update.c:383
#18 0xffffffffc04909e4 in __bch2_write_index (op=op@entry=0xffff888100f19290) at fs/bcachefs/io.c:784
#19 0xffffffffc04967c6 in bch2_write_point_do_index_updates (work=0xffff88819ae4eec0) at fs/bcachefs/io.c:891
#20 0xffffffff811380b3 in process_one_work (worker=worker@entry=0xffff88810022ab00, work=work@entry=0xffff88819ae4eec0) at kernel/workqueue.c:2289
#21 0xffffffff8113841e in worker_thread (__worker=0xffff88810022ab00) at kernel/workqueue.c:2436
#22 0xffffffff8114579c in kthread (_create=<optimized out>) at kernel/kthread.c:376
#23 0xffffffff81004a9c in ret_from_fork () at arch/x86/entry/entry_64.S:308
#24 0x0000000000000000 in ?? ()
```

Another backtrace that triggered kasan while I didn't have gdb attached:
```
[  236.013881] ==================================================================
[  236.019774] BUG: KASAN: slab-out-of-bounds in __bch2_alloc_to_v4_mut (fs/bcachefs/util.h:604 fs/bcachefs/bkey.h:543 fs/bcachefs/alloc_background.c:489) bcachefs
[  236.026098] Write of size 8 at addr ffff8881513a3100 by task kworker/u64:8/174

[  236.043405] Hardware name: Micro-Star International Co., Ltd. MS-7C91/MAG B550 TOMAHAWK (MS-7C91), BIOS A.61 02/26/2021
[  236.049589] Workqueue: bcachefs bch2_write_point_do_index_updates [bcachefs]
[  236.056372] Call Trace:
[  236.062578]  <TASK>
[  236.068714] dump_stack_lvl (lib/dump_stack.c:107 (discriminator 1)) 
[  236.074883] print_report (mm/kasan/report.c:307 mm/kasan/report.c:417) 
[  236.081057] ? __virt_addr_valid (./include/linux/mmzone.h:1783 ./include/linux/mmzone.h:1879 arch/x86/mm/physaddr.c:65) 
[  236.087185] ? __bch2_alloc_to_v4_mut (fs/bcachefs/util.h:604 fs/bcachefs/bkey.h:543 fs/bcachefs/alloc_background.c:489) bcachefs
[  236.094092] kasan_report (mm/kasan/report.c:184 mm/kasan/report.c:519) 
[  236.100465] ? __bch2_alloc_to_v4_mut (fs/bcachefs/util.h:604 fs/bcachefs/bkey.h:543 fs/bcachefs/alloc_background.c:489) bcachefs
[  236.107504] __bch2_alloc_to_v4_mut (fs/bcachefs/util.h:604 fs/bcachefs/bkey.h:543 fs/bcachefs/alloc_background.c:489) bcachefs
[  236.114540] ? __pfx___bch2_alloc_to_v4_mut (fs/bcachefs/alloc_background.c:479) bcachefs
[  236.121762] bch2_trans_start_alloc_update (fs/bcachefs/alloc_background.c:527 fs/bcachefs/alloc_background.c:552) bcachefs
[  236.129163] ? __pfx_bch2_trans_start_alloc_update (fs/bcachefs/alloc_background.c:538) bcachefs
[  236.136791] ? bch2_trans_mark_pointer.constprop.0 (fs/bcachefs/buckets.c:1420) bcachefs
[  236.144622] bch2_trans_mark_pointer.constprop.0 (fs/bcachefs/buckets.c:1420) bcachefs
```
([full version](https://github.com/koverstreet/bcachefs/files/11206808/kernel_bug_apr_11_decode.txt))

**Comment by koverstreet** [comment]
Fixed by 22ccceee15 bcachefs: Fix a slab-out-of-bounds
