### ISSUE TITLE
bcachefs-tools  Assertion `0' failed

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#532]
new issue : bch2_trans_in_restart_error: Assertion `0' failed

```
gdb -ex run --args bcachefs fsck -y  /dev/vdb
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bcachefs...
Starting program: /usr/sbin/bcachefs fsck -y /dev/vdb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7cb8600 (LWP 30450)]
[New Thread 0x7ffff7caf600 (LWP 30451)]
[New Thread 0x7ffff7ca6600 (LWP 30452)]
[New Thread 0x7ffff7c9d600 (LWP 30453)]
[New Thread 0x7ffff7c94600 (LWP 30454)]
[New Thread 0x7ffff7c8b600 (LWP 30455)]
[New Thread 0x7ffff7c82600 (LWP 30456)]
[New Thread 0x7ffff7c79600 (LWP 30457)]
[New Thread 0x7ffff7c70600 (LWP 30458)]
[New Thread 0x7ffff7c67600 (LWP 30459)]
[New Thread 0x7ffff7c5e600 (LWP 30460)]
[New Thread 0x7ffff7c55600 (LWP 30461)]
[New Thread 0x7ffff7c4c600 (LWP 30462)]
[New Thread 0x7ffff6ef7600 (LWP 30463)]
recovering from unclean shutdown
journal read done, replaying entries 12328043-12328043
dropped unflushed entries 12328044-12328044
[New Thread 0x7ffff6b46600 (LWP 30465)]
checking allocations
[New Thread 0x7fffe3fff600 (LWP 30466)]
starting journal replay, 933 keys
going read-write
[New Thread 0x7ffff6ab9600 (LWP 30471)]
[New Thread 0x7ffff6ab0600 (LWP 30472)]
journal replay done
checking need_discard and freespace btrees
checking lrus
checking backpointers to alloc keys
checking backpointers to extents
checking extents to backpointers
checking alloc to lru refs
starting fsck
snapshot deletion did not run correctly:
  duplicate keys in btree inodes at 0:536871740 snapshots 4294965113, 4294965115 (equiv 4294965113)
, fixing
check_inode(): error need_snapshot_cleanup
check_inodes(): error need_snapshot_cleanup



overlapping extents: extent in snapshot 4294965407 ends at 3938 overlaps with
u64s 7 type extent 1073741828:3968:4294965425 len 110 ver 0: durability: 1 crc: c_size 54 size 128 offset 0 nonce 0 csum crc32c compress lz4 ptr: 0:98223:0 gen 1, fixing
overlapping extents: extent in snapshot 4294965415 ends at 3948 overlaps with
u64s 7 type extent 1073741828:3968:4294965425 len 110 ver 0: durability: 1 crc: c_size 54 size 128 offset 0 nonce 0 csum crc32c compress lz4 ptr: 0:98223:0 gen 1, fixing
in transaction restart: transaction_restart_mem_realloced, last restarted by 0x5555555f4260S
bcachefs: libbcachefs/btree_iter.c:1369: bch2_trans_in_restart_error: Assertion `0' failed.

Thread 1 "bcachefs" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350704128) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350704128)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350704128) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350704128, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7a42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7a287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7a2871b in __assert_fail_base (
    fmt=0x7ffff7bdd150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55555584ba60 "0", 
    file=0x55555583e351 "libbcachefs/btree_iter.c", line=1369, function=<optimized out>)
    at ./assert/assert.c:92
#6  0x00007ffff7a39e96 in __GI___assert_fail (assertion=assertion@entry=0x55555584ba60 "0", 
    file=file@entry=0x55555583e351 "libbcachefs/btree_iter.c", line=line@entry=1369, 
    function=function@entry=0x55555583e8b0 <__PRETTY_FUNCTION__.15> "bch2_trans_in_restart_error")
    at ./assert/assert.c:101
#7  0x00005555555ee7b0 in bch2_trans_in_restart_error (trans=<optimized out>)
    at libbcachefs/btree_iter.c:1369
#8  0x00005555555f0839 in bch2_trans_verify_not_in_restart (trans=0x7fffffffd870)
    at libbcachefs/btree_iter.h:254
#9  bch2_path_get (trans=trans@entry=0x7fffffffd870, btree_id=BTREE_ID_extents, 
    btree_id@entry=4156412240, pos=..., locks_want=locks_want@entry=0, level=level@entry=0, 
    flags=4388, ip=93824993049533) at libbcachefs/btree_iter.c:1557
#10 0x00005555555f37d3 in bch2_trans_iter_init_common (ip=<optimized out>, flags=<optimized out>, 
    depth=0, locks_want=0, pos=..., btree_id=4156412240, iter=0x7fffffffd500, trans=0x7fffffffd870)
    at libbcachefs/btree_iter.h:417
#11 bch2_trans_iter_init_outlined (trans=trans@entry=0x7fffffffd870, iter=iter@entry=0x7fffffffd500, 
    btree_id=btree_id@entry=0, pos=..., flags=flags@entry=292) at libbcachefs/btree_iter.c:2754
#12 0x000055555561bbbd in bch2_trans_iter_init (flags=292, pos=..., btree_id=0, 
    iter=<optimized out>, trans=0x7fffffffd870) at libbcachefs/btree_iter.h:435
#13 bch2_trans_update_extent (trans=trans@entry=0x7fffffffd870, 
    orig_iter=orig_iter@entry=0x7fffffffd750, insert=0x555555b1d338, 
    flags=flags@entry=__BTREE_UPDATE_INTERNAL_SNAPSHOT_NODE) at libbcachefs/btree_update_leaf.c:1358
#14 0x0000555555659397 in check_overlapping_extents (iter=0x7fffffffd750, k=..., 
    extent_ends=0x7fffffffd6a0, seen=0x7fffffffd6f0, trans=0x7fffffffd870) at libbcachefs/fsck.c:1216
#15 check_extent (extent_ends=0x7fffffffd6a0, s=0x7fffffffd6f0, inode=0x7fffffffd6c0, k=..., 
    iter=0x7fffffffd750, trans=0x7fffffffd870) at libbcachefs/fsck.c:1305
#16 check_extents (c=c@entry=0x7ffff797f000) at libbcachefs/fsck.c:1419
#17 0x000055555565f6d9 in bch2_fsck_full (c=c@entry=0x7ffff797f000) at libbcachefs/fsck.c:2471
#18 0x00005555556108ed in bch2_fs_recovery (c=0x7ffff797f000) at libbcachefs/recovery.c:1427
#19 0x000055555562446d in bch2_fs_start (c=c@entry=0x7ffff797f000) at libbcachefs/super.c:935
#20 0x0000555555627027 in bch2_fs_open (devices=devices@entry=0x7fffffffe3c8, 
    nr_devices=<optimized out>, nr_devices@entry=1, opts=...) at libbcachefs/super.c:1923
#21 0x00005555555a36c3 in cmd_fsck (argc=1, argv=0x7fffffffe3c8, argv@entry=0x7fffffffe3b8)
    at cmd_fsck.c:96
#22 0x0000555555599d99 in main (argc=<optimized out>, argv=0x7fffffffe3b8) at bcachefs.c:201
(gdb) bt full
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350704128)
    at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7ffff7cb9c00
        old_mask = {__val = {93824997587588, 93824997587488, 93824997587588, 0, 0, 0, 0, 0, 
            551212974264, 93824992857037, 0, 0, 93825001995776, 5213245811079677696, 
            18446744073709551615, 5213245811079677696}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140737350704128) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=140737350704128, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007ffff7a42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007ffff7a287f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x555555a6fa20, sa_sigaction = 0x555555a6fa20}, 
          sa_mask = {__val = {0, 93824997587488, 2147483647, 4, 140737349780746, 0, 10022240864, 
              140737488343584, 5213245811079677696, 0, 18446744073709550264, 2, 93824995287889, 
              1369, 93824995342944, 4294965425}}, sa_flags = -139832109, 
          sa_restorer = 0x7ffff7c16600 <_IO_file_jumps>}
        sigs = {__val = {32, 140737350051488, 93824995287889, 1369, 93824995342944, 4294965425, 
            140737350704128, 140737348364654, 206158430256, 140737488343808, 206158430232, 
--Type <RET> for more, q to quit, c to continue without paging--
            140737488343808, 140737488343600, 5213245811079677696, 140737488348739, 140737349781186}}
#5  0x00007ffff7a2871b in __assert_fail_base (
    fmt=0x7ffff7bdd150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55555584ba60 "0", 
    file=0x55555583e351 "libbcachefs/btree_iter.c", line=1369, function=<optimized out>)
    at ./assert/assert.c:92
        str = 0x555555a6fa20 <incomplete sequence \363>
        total = 4096
#6  0x00007ffff7a39e96 in __GI___assert_fail (assertion=assertion@entry=0x55555584ba60 "0", 
    file=file@entry=0x55555583e351 "libbcachefs/btree_iter.c", line=line@entry=1369, 
    function=function@entry=0x55555583e8b0 <__PRETTY_FUNCTION__.15> "bch2_trans_in_restart_error")
    at ./assert/assert.c:101
No locals.
#7  0x00005555555ee7b0 in bch2_trans_in_restart_error (trans=<optimized out>)
    at libbcachefs/btree_iter.c:1369
        __PRETTY_FUNCTION__ = "bch2_trans_in_restart_error"
#8  0x00005555555f0839 in bch2_trans_verify_not_in_restart (trans=0x7fffffffd870)
    at libbcachefs/btree_iter.h:254
No locals.
#9  bch2_path_get (trans=trans@entry=0x7fffffffd870, btree_id=BTREE_ID_extents, 
    btree_id@entry=4156412240, pos=..., locks_want=locks_want@entry=0, level=level@entry=0, 
    flags=4388, ip=93824993049533) at libbcachefs/btree_iter.c:1557
        path = <optimized out>
        path_pos = 0x0
        cached = false
        intent = true
        i = <optimized out>
#10 0x00005555555f37d3 in bch2_trans_iter_init_common (ip=<optimized out>, flags=<optimized out>, 
    depth=0, locks_want=0, pos=..., btree_id=4156412240, iter=0x7fffffffd500, trans=0x7fffffffd870)
    at libbcachefs/btree_iter.h:417
No locals.
#11 bch2_trans_iter_init_outlined (trans=trans@entry=0x7fffffffd870, iter=iter@entry=0x7fffffffd500, 
    btree_id=btree_id@entry=0, pos=..., flags=flags@entry=292) at libbcachefs/btree_iter.c:2754
No locals.
#12 0x000055555561bbbd in bch2_trans_iter_init (flags=292, pos=..., btree_id=0, 
    iter=<optimized out>, trans=0x7fffffffd870) at libbcachefs/btree_iter.h:435
        __here = <optimized out>
#13 bch2_trans_update_extent (trans=trans@entry=0x7fffffffd870, 
    orig_iter=orig_iter@entry=0x7fffffffd750, insert=0x555555b1d338, 
    flags=flags@entry=__BTREE_UPDATE_INTERNAL_SNAPSHOT_NODE) at libbcachefs/btree_update_leaf.c:1358
        iter = {trans = 0x7fffffffd870, path = 0x0, update_path = 0x0, key_cache_path = 0x0, 
          btree_id = BTREE_ID_extents, min_depth = 0, advanced = 0, flags = 4388, 
          snapshot = 4294965425, pos = {snapshot = 4294965425, offset = 3858, inode = 1073741828}, 
          k = {u64s = 0 '\000', format = 0 '\000', needs_whiteout = 0 '\000', type = 0 '\000', 
            pad = "", version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 4294965425, 
              offset = 3858, inode = 1073741828}}, journal_idx = 0, journal_pos = {snapshot = 0, 
            offset = 0, inode = 0}}
        start = {snapshot = 4294965425, offset = 3858, inode = 1073741828}
        update = <optimized out>
        k = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        btree_id = BTREE_ID_extents
        ret = 0
        compressed_sectors = <optimized out>
        out = <optimized out>
#14 0x0000555555659397 in check_overlapping_extents (iter=0x7fffffffd750, k=..., 
    extent_ends=0x7fffffffd6a0, seen=0x7fffffffd6f0, trans=0x7fffffffd870) at libbcachefs/fsck.c:1216
        update = <optimized out>
        c = 0x7ffff797f000
        i = 0x555556e33dc0
        buf = {
          buf = 0x555555b01d00 "u64s 7 type extent 1073741828:3968:4294965425 len 110 ver 0: durability: 1 crc: c_size 54 size 128 offset 0 nonce 0 csum crc32c compress lz4 ptr: 0:98223:0 gen 1", 
          size = 256, pos = 161, last_newline = 0, last_field = 0, indent = 0, atomic = 0 '\000', 
          allocation_failure = false, heap_allocated = true, si_units = PRINTBUF_UNITS_2, 
          human_readable_units = false, has_indent_or_tabstops = false, 
          suppress_indent_tabstop_handling = false, nr_tabstops = 0 '\000', cur_tabstop = 0 '\000', 
          _tabstops = "\000\000\000\000\000"}
        ret = <optimized out>
        c = <optimized out>
        i = <optimized out>
        buf = <optimized out>
        ret = <optimized out>
        fsck_err = <optimized out>
        err = <optimized out>
        _ret = <optimized out>
        update = <optimized out>
#15 check_extent (extent_ends=0x7fffffffd6a0, s=0x7fffffffd6f0, inode=0x7fffffffd6c0, k=..., 
    iter=0x7fffffffd750, trans=0x7fffffffd870) at libbcachefs/fsck.c:1305
        c = <optimized out>
        i = <optimized out>
        buf = {buf = 0x0, size = 0, pos = 0, last_newline = 0, last_field = 0, indent = 0, 
          atomic = 0 '\000', allocation_failure = false, heap_allocated = true, 
          si_units = PRINTBUF_UNITS_2, human_readable_units = false, has_indent_or_tabstops = false, 
          suppress_indent_tabstop_handling = false, nr_tabstops = 0 '\000', cur_tabstop = 0 '\000', 
          _tabstops = "\000\000\000\000\000"}
        ret = <optimized out>
        equiv = <optimized out>
        c = <optimized out>
        i = <optimized out>
        buf = <optimized out>
        equiv = <optimized out>
        ret = <optimized out>
        out = <optimized out>
        err = <optimized out>
        __PRETTY_FUNCTION__ = "check_extent"
        fsck_err = <optimized out>
        __func__ = "check_extent"
        _ret = <optimized out>
        _ret = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        _ret = <optimized out>
        iter2 = <optimized out>
#16 check_extents (c=c@entry=0x7ffff797f000) at libbcachefs/fsck.c:1419
        _restart_count = <optimized out>
        _ret = 0
        w = {first_this_inode = false, cur_inum = 1073741828, inodes = {nr = 90, size = 512, 
            data = 0x555556dc2000}}
        s = {pos = {snapshot = 4294965425, offset = 3968, inode = 1073741828}, ids = {nr = 34, 
            size = 512, data = 0x555556e89000}}
        trans = {c = 0x7ffff797f000, fn = 0x55555584d5d0 <__func__.33> "check_extents", ref = {{{
                wq = 0x0, s = 0x0, list = {next = 0x0}, fn = 0x0}, work = {data = {counter = 0}, 
                entry = {next = 0x0, prev = 0x0}, func = 0x0}}, parent = 0x0, remaining = {
              counter = 1073741825}}, list = {next = 0x0, prev = 0x0}, 
          last_begin_time = 5899435933459, lock_may_not_fail = 0 '\000', lock_must_abort = 0 '\000', 
          locking = 0x0, locking_wait = {list = {next = 0x0, prev = 0x0}, task = 0x555555a6a2a0, 
            lock_want = SIX_LOCK_read, lock_acquired = false, start_time = 0}, srcu_idx = 0, 
          fn_idx = 31 '\037', nr_sorted = 2 '\002', nr_updates = 0 '\000', nr_wb_updates = 0 '\000', 
          wb_updates_size = 0 '\000', used_mempool = false, in_traverse_all = false, 
          paths_sorted = false, memory_allocation_failure = false, 
          journal_transaction_names = false, journal_replay_not_finished = false, 
          is_initial_gc = false, notrace_relock_fail = false, 
          restarted = BCH_ERR_transaction_restart_mem_realloced, restart_count = 10140759, 
          last_begin_ip = 93824993299124, last_restarted_ip = 93824992887392, 
          srcu_lock_time = 5899428, extra_journal_res = 0, nr_max_paths = 2, paths_allocated = 3, 
          mem_top = 112, mem_max = 112, mem_bytes = 128, mem = 0x555555b1d300, 
          sorted = "\000\001\002", '\000' <repeats 68 times>, paths = 0x555556da8000, 
          updates = 0x555556daa000, wb_updates = 0x0, hooks = 0x0, extra_journal_entries = {nr = 0, 
            size = 0, data = 0x0}, journal_pin = 0x0, journal_res = {ref = false, idx = 0 '\000', 
            u64s = 0, offset = 0, seq = 0}, journal_preres = {u64s = 0}, journal_seq = 0x0, 
          disk_res = 0x7fffffffd650, journal_u64s = 0, journal_preres_u64s = 0, 
          fs_usage_deltas = 0x0}
        iter = {trans = 0x7fffffffd870, path = 0x555556da8000, update_path = 0x0, 
          key_cache_path = 0x0, btree_id = BTREE_ID_extents, min_depth = 0, advanced = 0, 
          flags = 2056, snapshot = 0, pos = {snapshot = 4294965425, offset = 3968, 
            inode = 1073741828}, k = {u64s = 7 '\a', format = 1 '\001', needs_whiteout = 1 '\001', 
            type = 6 '\006', pad = "", version = {lo = 0, hi = 0}, size = 110, p = {
              snapshot = 4294965425, offset = 3968, inode = 1073741828}}, journal_idx = 0, 
          journal_pos = {snapshot = 0, offset = 0, inode = 0}}
        k = <optimized out>
        extent_ends = {nr = 92, size = 512, data = 0x555556e33000}
        res = {sectors = 0, gen = 0, nr_replicas = 0}
        ret = 0
        __func__ = "check_extents"
#17 0x000055555565f6d9 in bch2_fsck_full (c=c@entry=0x7ffff797f000) at libbcachefs/fsck.c:2471
        ret = <optimized out>
#18 0x00005555556108ed in bch2_fs_recovery (c=0x7ffff797f000) at libbcachefs/recovery.c:1427
        err = 0x555555843ca6 "error in fsck"
        clean = <optimized out>
        last_journal_entry = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        last_seq = 12328043
        blacklist_seq = 12328044
        journal_seq = 12328053
        write_sb = false
        ret = <optimized out>
        __func__ = "bch2_fs_recovery"
#19 0x000055555562446d in bch2_fs_start (c=c@entry=0x7ffff797f000) at libbcachefs/super.c:935
        mi = 0x555555a702f0
        ca = <optimized out>
        now = <optimized out>
        i = <optimized out>
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "bch2_fs_start"
#20 0x0000555555627027 in bch2_fs_open (devices=devices@entry=0x7fffffffe3c8, 
    nr_devices=<optimized out>, nr_devices@entry=1, opts=...) at libbcachefs/super.c:1923
        sb = <optimized out>
        c = 0x7ffff797f000
        mi = <optimized out>
        i = <optimized out>
        best_sb = <optimized out>
        errbuf = {buf = 0x0, size = 0, pos = 0, last_newline = 0, last_field = 0, indent = 0, 
          atomic = 0 '\000', allocation_failure = false, heap_allocated = true, 
          si_units = PRINTBUF_UNITS_2, human_readable_units = false, has_indent_or_tabstops = false, 
          suppress_indent_tabstop_handling = false, nr_tabstops = 0 '\000', cur_tabstop = 0 '\000', 
          _tabstops = "\000\000\000\000\000"}
        ret = <optimized out>
        __func__ = "bch2_fs_open"
#21 0x00005555555a36c3 in cmd_fsck (argc=1, argv=0x7fffffffe3c8, argv@entry=0x7fffffffe3b8)
    at cmd_fsck.c:96
        longopts = {{name = 0x5555558353f0 "ratelimit_errors", has_arg = 0, flag = 0x0, val = 114}, {
            name = 0x555555835401 "reconstruct_alloc", has_arg = 0, flag = 0x0, val = 82}, {
            name = 0x55555583268a "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x0, 
            has_arg = 0, flag = 0x0, val = 0}}
        opts = {block_size_defined = 0, btree_node_size_defined = 0, errors_defined = 0, 
          metadata_replicas_defined = 0, data_replicas_defined = 0, 
          metadata_replicas_required_defined = 0, data_replicas_required_defined = 0, 
          encoded_extent_max_defined = 0, metadata_checksum_defined = 0, data_checksum_defined = 0, 
          compression_defined = 0, background_compression_defined = 0, str_hash_defined = 0, 
          metadata_target_defined = 0, foreground_target_defined = 0, background_target_defined = 0, 
          promote_target_defined = 0, erasure_code_defined = 0, inodes_32bit_defined = 0, 
          shard_inode_numbers_defined = 0, inodes_use_key_cache_defined = 0, 
          btree_node_mem_ptr_optimization_defined = 0, btree_write_buffer_size_defined = 0, 
          gc_reserve_percent_defined = 0, gc_reserve_bytes_defined = 0, 
          root_reserve_percent_defined = 0, wide_macs_defined = 0, inline_data_defined = 0, 
          acl_defined = 0, usrquota_defined = 0, grpquota_defined = 0, prjquota_defined = 0, 
          degraded_defined = 1, very_degraded_defined = 0, discard_defined = 0, verbose_defined = 0, 
          journal_flush_delay_defined = 0, journal_flush_disabled_defined = 0, 
          journal_reclaim_delay_defined = 0, move_bytes_in_flight_defined = 0, 
          move_ios_in_flight_defined = 0, fsck_defined = 1, fix_errors_defined = 1, 
--Type <RET> for more, q to quit, c to continue without paging--
          ratelimit_errors_defined = 0, nochanges_defined = 0, norecovery_defined = 0, 
          keep_journal_defined = 0, read_entire_journal_defined = 0, read_journal_only_defined = 0, 
          journal_transaction_names_defined = 0, noexcl_defined = 0, direct_io_defined = 0, 
          sb_defined = 0, read_only_defined = 0, nostart_defined = 0, reconstruct_alloc_defined = 0, 
          version_upgrade_defined = 0, buckets_nouse_defined = 0, project_defined = 0, 
          nocow_defined = 0, nocow_enabled_defined = 0, no_data_io_defined = 0, fs_size_defined = 0, 
          bucket_defined = 0, durability_defined = 0, block_size = 0, btree_node_size = 0, 
          errors = 0 '\000', metadata_replicas = 0 '\000', data_replicas = 0 '\000', 
          metadata_replicas_required = 0 '\000', data_replicas_required = 0 '\000', 
          encoded_extent_max = 0, metadata_checksum = 0 '\000', data_checksum = 0 '\000', 
          compression = 0 '\000', background_compression = 0 '\000', str_hash = 0 '\000', 
          metadata_target = 0, foreground_target = 0, background_target = 0, promote_target = 0, 
          erasure_code = 0, inodes_32bit = 0 '\000', shard_inode_numbers = 0 '\000', 
          inodes_use_key_cache = 0 '\000', btree_node_mem_ptr_optimization = 0 '\000', 
          btree_write_buffer_size = 0, gc_reserve_percent = 0 '\000', gc_reserve_bytes = 0, 
          root_reserve_percent = 0 '\000', wide_macs = 0 '\000', inline_data = 0 '\000', 
          acl = 0 '\000', usrquota = 0 '\000', grpquota = 0 '\000', prjquota = 0 '\000', 
          degraded = 1 '\001', very_degraded = 0 '\000', discard = 0 '\000', verbose = 0 '\000', 
          journal_flush_delay = 0, journal_flush_disabled = 0 '\000', journal_reclaim_delay = 0, 
          move_bytes_in_flight = 0, move_ios_in_flight = 0, fsck = 1 '\001', fix_errors = 1 '\001', 
          ratelimit_errors = 0 '\000', nochanges = 0 '\000', norecovery = 0 '\000', 
          keep_journal = 0 '\000', read_entire_journal = 0 '\000', read_journal_only = 0 '\000', 
          journal_transaction_names = 0 '\000', noexcl = 0 '\000', direct_io = 0 '\000', sb = 0, 
          read_only = 0 '\000', nostart = 0 '\000', reconstruct_alloc = 0 '\000', 
          version_upgrade = 0 '\000', buckets_nouse = 0 '\000', project = 0 '\000', 
          nocow = 0 '\000', nocow_enabled = 0 '\000', no_data_io = 0 '\000', fs_size = 0, 
          bucket = 0, durability = 0 '\000'}
        i = 1
        opt = <optimized out>
        ret = 0
        c = <optimized out>
#22 0x0000555555599d99 in main (argc=<optimized out>, argv=0x7fffffffe3b8) at bcachefs.c:201
        cmd = 0x7fffffffe64c "fsck"
(gdb) 
```

**Comment by koverstreet** [comment]
This should be fixed now, reopen if needed
