### ISSUE TITLE
bcachefs-tools  bch2_trans_in_restart_error: Assertion `0' failed

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#539]
bcachefs-tools  bch2_trans_in_restart_error: Assertion `0' failed

version 6e897639569207885257ac744019b7e5c340fb74

```
starting fsck
overlapping extents: extent in snapshot 4294966877 ends at 4096 overlaps with
u64s 7 type extent 4098:4101:U32_MAX len 21 ver 0: durability: 1 crc: c_size 36 size 128 offset 0 nonce 0 csum crc32c compress lz4 ptr: 0:8209:385 gen 2, fixing
overlapping extents: extent in snapshot 4294967197 ends at 4096 overlaps with
u64s 7 type extent 4098:4101:U32_MAX len 21 ver 0: durability: 1 crc: c_size 36 size 128 offset 0 nonce 0 csum crc32c compress lz4 ptr: 0:8209:385 gen 2, fixing
in transaction restart: transaction_restart_mem_realloced, last restarted by 0x558b38d8a470S
bcachefs: libbcachefs/btree_iter.c:1369: bch2_trans_in_restart_error: Assertion `0' failed.

[1]+  Aborted                 (core dumped) bcachefs fsck -y /dev/vdb
root@slave-test:~# ^Cachefs fsck -y /dev/vdb &
root@slave-test:~# history | grep gdb
 1284  gdb -ex run --args bcachefs fsck -y  /dev/vdb
 1296  gdb -ex run --args bcachefs fsck -y  /dev/vdb
 1318  gdb -ex run --args bcachefs fsck -y  /dev/vdb
 1320  gdb -ex run --args bcachefs fsck -y  /dev/vdb
 1329  gdb -ex run --args bcachefs fsck -y  /dev/vdb
 1724  history | grep gdb
root@slave-test:~# gdb -ex run --args bcachefs fsck -y  /dev/vdb
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bcachefs...
Starting program: /usr/sbin/bcachefs fsck -y /dev/vdb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7cb8600 (LWP 4321)]
[New Thread 0x7ffff7caf600 (LWP 4322)]
[New Thread 0x7ffff7ca6600 (LWP 4323)]
[New Thread 0x7ffff7c9d600 (LWP 4324)]
[New Thread 0x7ffff7c94600 (LWP 4325)]
[New Thread 0x7ffff7c8b600 (LWP 4326)]
[New Thread 0x7ffff7c82600 (LWP 4327)]
[New Thread 0x7ffff7c79600 (LWP 4328)]
[New Thread 0x7ffff7c70600 (LWP 4329)]
[New Thread 0x7ffff7c67600 (LWP 4330)]
[New Thread 0x7ffff7c5e600 (LWP 4331)]
[New Thread 0x7ffff7c55600 (LWP 4332)]
[New Thread 0x7ffff7c4c600 (LWP 4333)]
[New Thread 0x7ffff6ef7600 (LWP 4334)]
recovering from unclean shutdown
journal read done, replaying entries 8508556-8508556
[New Thread 0x7ffff6b46600 (LWP 4336)]
checking allocations
[New Thread 0x7fffe3fff600 (LWP 4337)]
starting journal replay, 0 keys
journal replay done
checking need_discard and freespace btrees
checking lrus
checking backpointers to alloc keys
checking backpointers to extents
checking extents to backpointers
checking alloc to lru refs
starting fsck
overlapping extents: extent in snapshot 4294966877 ends at 4096 overlaps with
u64s 7 type extent 4098:4101:U32_MAX len 21 ver 0: durability: 1 crc: c_size 36 size 128 offset 0 nonce 0 csum crc32c compress lz4 ptr: 0:8209:385 gen 2, fixing
overlapping extents: extent in snapshot 4294967197 ends at 4096 overlaps with
u64s 7 type extent 4098:4101:U32_MAX len 21 ver 0: durability: 1 crc: c_size 36 size 128 offset 0 nonce 0 csum crc32c compress lz4 ptr: 0:8209:385 gen 2, fixing
in transaction restart: transaction_restart_mem_realloced, last restarted by 0x5555555f4470S
bcachefs: libbcachefs/btree_iter.c:1369: bch2_trans_in_restart_error: Assertion `0' failed.

Thread 1 "bcachefs" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350704128) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350704128) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350704128) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350704128, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7a42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7a287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7a2871b in __assert_fail_base (fmt=0x7ffff7bdd150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x55555584ed00 "0", file=0x555555841311 "libbcachefs/btree_iter.c", line=1369, function=<optimized out>)
    at ./assert/assert.c:92
#6  0x00007ffff7a39e96 in __GI___assert_fail (assertion=assertion@entry=0x55555584ed00 "0", 
    file=file@entry=0x555555841311 "libbcachefs/btree_iter.c", line=line@entry=1369, 
    function=function@entry=0x555555841870 <__PRETTY_FUNCTION__.15> "bch2_trans_in_restart_error") at ./assert/assert.c:101
#7  0x00005555555ee9c0 in bch2_trans_in_restart_error (trans=<optimized out>) at libbcachefs/btree_iter.c:1369
#8  0x00005555555f0a49 in bch2_trans_verify_not_in_restart (trans=0x7fffffffd850) at libbcachefs/btree_iter.h:260
#9  bch2_path_get (trans=0x7fffffffd850, trans@entry=0xff0, btree_id=btree_id@entry=BTREE_ID_extents, pos=..., 
    locks_want=locks_want@entry=0, level=level@entry=0, flags=4388, ip=93824993050226) at libbcachefs/btree_iter.c:1557
#10 0x00005555555f39e3 in bch2_trans_iter_init_common (ip=<optimized out>, flags=<optimized out>, depth=0, locks_want=0, 
    pos=..., btree_id=0, iter=0x7fffffffd4e0, trans=0xff0) at libbcachefs/btree_iter.h:423
#11 bch2_trans_iter_init_outlined (trans=trans@entry=0x7fffffffd850, iter=iter@entry=0x7fffffffd4e0, 
    btree_id=btree_id@entry=0, pos=..., flags=flags@entry=292) at libbcachefs/btree_iter.c:2754
#12 0x000055555561be72 in bch2_trans_iter_init (flags=292, pos=..., btree_id=0, iter=<optimized out>, trans=0x7fffffffd850)
    at libbcachefs/btree_iter.h:441
#13 bch2_trans_update_extent (trans=trans@entry=0x7fffffffd850, orig_iter=orig_iter@entry=0x7fffffffd730, 
    insert=0x555555b0a338, flags=flags@entry=0) at libbcachefs/btree_update_leaf.c:1358
#14 0x000055555565b2d7 in check_overlapping_extents (iter=0x7fffffffd730, k=..., extent_ends=0x7fffffffd680, 
    seen=0x7fffffffd6d0, trans=0x7fffffffd850) at libbcachefs/fsck.c:1178
#15 check_extent (extent_ends=0x7fffffffd680, s=0x7fffffffd6d0, inode=0x7fffffffd6a0, k=..., iter=0x7fffffffd730, 
    trans=0x7fffffffd850) at libbcachefs/fsck.c:1267
#16 check_extents (c=c@entry=0x7ffff797f000) at libbcachefs/fsck.c:1381
#17 0x0000555555661871 in bch2_fsck_full (c=c@entry=0x7ffff797f000) at libbcachefs/fsck.c:2435
#18 0x0000555555610b8a in bch2_fs_recovery (c=0x7ffff797f000) at libbcachefs/recovery.c:1439
#19 0x000055555562496d in bch2_fs_start (c=c@entry=0x7ffff797f000) at libbcachefs/super.c:934
#20 0x0000555555627567 in bch2_fs_open (devices=devices@entry=0x7fffffffe3a8, nr_devices=<optimized out>, 
    nr_devices@entry=1, opts=...) at libbcachefs/super.c:1924
#21 0x00005555555a36d3 in cmd_fsck (argc=1, argv=0x7fffffffe3a8, argv@entry=0x7fffffffe398) at cmd_fsck.c:96
#22 0x0000555555599da9 in main (argc=<optimized out>, argv=0x7fffffffe398) at bcachefs.c:205
(gdb) bt full
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350704128) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7ffff7cb9c00
        old_mask = {__val = {93824997608068, 93824997607968, 93824997608068, 0, 0, 0, 0, 0, 551212974264, 93824992857565, 0, 
            0, 93824999464448, 589815251261530624, 18446744073709551615, 589815251261530624}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140737350704128) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=140737350704128, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007ffff7a42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007ffff7a287f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x555555a74a20, sa_sigaction = 0x555555a74a20}, sa_mask = {__val = {0, 
              93824997607968, 2147483647, 4, 140737349780746, 0, 10022241392, 140737488343536, 589815251261530624, 0, 
              18446744073709550264, 2, 93824995300113, 1369, 93824995355904, 0}}, sa_flags = -139832109, 
          sa_restorer = 0x7ffff7c16600 <_IO_file_jumps>}
        sigs = {__val = {32, 140737350051488, 93824995300113, 1369, 93824995355904, 0, 140737350704128, 140737348364654, 
            206158430256, 140737488343760, 206158430232, 140737488343760, 140737488343552, 589815251261530624, 
--Type <RET> for more, q to quit, c to continue without paging--
            140737488348740, 140737349781186}}
#5  0x00007ffff7a2871b in __assert_fail_base (fmt=0x7ffff7bdd150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x55555584ed00 "0", file=0x555555841311 "libbcachefs/btree_iter.c", line=1369, function=<optimized out>)
    at ./assert/assert.c:92
        str = 0x555555a74a20 "\304", <incomplete sequence \362>
        total = 4096
#6  0x00007ffff7a39e96 in __GI___assert_fail (assertion=assertion@entry=0x55555584ed00 "0", 
    file=file@entry=0x555555841311 "libbcachefs/btree_iter.c", line=line@entry=1369, 
    function=function@entry=0x555555841870 <__PRETTY_FUNCTION__.15> "bch2_trans_in_restart_error") at ./assert/assert.c:101
No locals.
#7  0x00005555555ee9c0 in bch2_trans_in_restart_error (trans=<optimized out>) at libbcachefs/btree_iter.c:1369
        __PRETTY_FUNCTION__ = "bch2_trans_in_restart_error"
#8  0x00005555555f0a49 in bch2_trans_verify_not_in_restart (trans=0x7fffffffd850) at libbcachefs/btree_iter.h:260
No locals.
#9  bch2_path_get (trans=0x7fffffffd850, trans@entry=0xff0, btree_id=btree_id@entry=BTREE_ID_extents, pos=..., 
    locks_want=locks_want@entry=0, level=level@entry=0, flags=4388, ip=93824993050226) at libbcachefs/btree_iter.c:1557
        path = <optimized out>
        path_pos = 0x0
        cached = false
        intent = true
        i = <optimized out>
#10 0x00005555555f39e3 in bch2_trans_iter_init_common (ip=<optimized out>, flags=<optimized out>, depth=0, locks_want=0, 
    pos=..., btree_id=0, iter=0x7fffffffd4e0, trans=0xff0) at libbcachefs/btree_iter.h:423
No locals.
#11 bch2_trans_iter_init_outlined (trans=trans@entry=0x7fffffffd850, iter=iter@entry=0x7fffffffd4e0, 
    btree_id=btree_id@entry=0, pos=..., flags=flags@entry=292) at libbcachefs/btree_iter.c:2754
No locals.
#12 0x000055555561be72 in bch2_trans_iter_init (flags=292, pos=..., btree_id=0, iter=<optimized out>, trans=0x7fffffffd850)
    at libbcachefs/btree_iter.h:441
        __here = <optimized out>
#13 bch2_trans_update_extent (trans=trans@entry=0x7fffffffd850, orig_iter=orig_iter@entry=0x7fffffffd730, 
    insert=0x555555b0a338, flags=flags@entry=0) at libbcachefs/btree_update_leaf.c:1358
        iter = {trans = 0x7fffffffd850, path = 0x0, update_path = 0x0, key_cache_path = 0x0, btree_id = BTREE_ID_extents, 
          min_depth = 0, advanced = 0, flags = 4388, snapshot = 4294967295, pos = {snapshot = 4294967295, offset = 4080, 
            inode = 4098}, k = {u64s = 0 '\000', format = 0 '\000', needs_whiteout = 0 '\000', type = 0 '\000', pad = "", 
            version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 4294967295, offset = 4080, inode = 4098}}, 
          journal_idx = 0, journal_pos = {snapshot = 0, offset = 0, inode = 0}}
        start = {snapshot = <optimized out>, offset = 4080, inode = 4098}
        update = <optimized out>
        k = <optimized out>
        btree_id = BTREE_ID_extents
        ret = 0
        compressed_sectors = <optimized out>
        out = <optimized out>
#14 0x000055555565b2d7 in check_overlapping_extents (iter=0x7fffffffd730, k=..., extent_ends=0x7fffffffd680, 
    seen=0x7fffffffd6d0, trans=0x7fffffffd850) at libbcachefs/fsck.c:1178
--Type <RET> for more, q to quit, c to continue without paging--
        update = <optimized out>
        c = 0x7ffff797f000
        i = 0x555556dbbe00
        buf = {
          buf = 0x555556daf200 "u64s 7 type extent 4098:4101:U32_MAX len 21 ver 0: durability: 1 crc: c_size 36 size 128 offset 0 nonce 0 csum crc32c compress lz4 ptr: 0:8209:385 gen 2", size = 256, pos = 152, last_newline = 0, last_field = 0, 
          indent = 0, atomic = 0 '\000', allocation_failure = false, heap_allocated = true, si_units = PRINTBUF_UNITS_2, 
          human_readable_units = false, has_indent_or_tabstops = false, suppress_indent_tabstop_handling = false, 
          nr_tabstops = 0 '\000', cur_tabstop = 0 '\000', _tabstops = "\000\000\000\000\000"}
        ret = <optimized out>
        c = <optimized out>
        i = <optimized out>
        buf = <optimized out>
        ret = <optimized out>
        fsck_err = <optimized out>
        err = <optimized out>
        _ret = <optimized out>
        update = <optimized out>
#15 check_extent (extent_ends=0x7fffffffd680, s=0x7fffffffd6d0, inode=0x7fffffffd6a0, k=..., iter=0x7fffffffd730, 
    trans=0x7fffffffd850) at libbcachefs/fsck.c:1267
        c = <optimized out>
        i = <optimized out>
        buf = {buf = 0x0, size = 0, pos = 0, last_newline = 0, last_field = 0, indent = 0, atomic = 0 '\000', 
          allocation_failure = false, heap_allocated = true, si_units = PRINTBUF_UNITS_2, human_readable_units = false, 
          has_indent_or_tabstops = false, suppress_indent_tabstop_handling = false, nr_tabstops = 0 '\000', 
          cur_tabstop = 0 '\000', _tabstops = "\000\000\000\000\000"}
        ret = <optimized out>
        equiv = <optimized out>
        c = <optimized out>
        i = <optimized out>
        buf = <optimized out>
        equiv = <optimized out>
        ret = <optimized out>
        out = <optimized out>
        err = <optimized out>
        __PRETTY_FUNCTION__ = "check_extent"
        fsck_err = <optimized out>
        __func__ = "check_extent"
        _ret = <optimized out>
        _ret = <optimized out>
        _ret = <optimized out>
        iter2 = <optimized out>
#16 check_extents (c=c@entry=0x7ffff797f000) at libbcachefs/fsck.c:1381
        _restart_count = <optimized out>
        _ret = 0
        w = {first_this_inode = true, cur_inum = 4098, inodes = {nr = 122, size = 128, data = 0x555556db2000}}
--Type <RET> for more, q to quit, c to continue without paging--
        s = {pos = {snapshot = 4294967295, offset = 4101, inode = 4098}, ids = {nr = 7, size = 128, data = 0x555556dad000}}
        trans = {c = 0x7ffff797f000, fn = 0x555555850850 <__func__.33> "check_extents", ref = {{{wq = 0x0, s = 0x0, list = {
                  next = 0x0}, fn = 0x0}, work = {data = {counter = 0}, entry = {next = 0x0, prev = 0x0}, func = 0x0}}, 
            parent = 0x0, remaining = {counter = 1073741825}}, list = {next = 0x0, prev = 0x0}, 
          last_begin_time = 10983196345739, lock_may_not_fail = 0 '\000', lock_must_abort = 0 '\000', locking = 0x0, 
          locking_wait = {list = {next = 0x0, prev = 0x0}, task = 0x555555a6f2a0, lock_want = SIX_LOCK_read, 
            lock_acquired = false, start_time = 0}, srcu_idx = 0, fn_idx = 21 '\025', nr_sorted = 2 '\002', 
          nr_updates = 0 '\000', nr_wb_updates = 0 '\000', wb_updates_size = 0 '\000', used_mempool = false, 
          in_traverse_all = false, paths_sorted = false, memory_allocation_failure = false, 
          journal_transaction_names = false, journal_replay_not_finished = false, is_initial_gc = false, 
          notrace_relock_fail = false, restarted = BCH_ERR_transaction_restart_mem_realloced, restart_count = 8527, 
          last_begin_ip = 93824993307124, last_restarted_ip = 93824992887920, srcu_lock_time = 10983189, 
          extra_journal_res = 0, nr_max_paths = 2, paths_allocated = 3, mem_top = 112, mem_max = 112, mem_bytes = 128, 
          mem = 0x555555b0a300, sorted = "\000\001\002", '\000' <repeats 68 times>, paths = 0x555556da8000, 
          updates = 0x555556daa000, wb_updates = 0x0, hooks = 0x0, extra_journal_entries = {nr = 0, size = 0, data = 0x0}, 
          journal_pin = 0x0, journal_res = {ref = false, idx = 0 '\000', u64s = 0, offset = 0, seq = 0}, journal_preres = {
            u64s = 0}, journal_seq = 0x0, disk_res = 0x7fffffffd630, journal_u64s = 0, journal_preres_u64s = 0, 
          fs_usage_deltas = 0x0}
        iter = {trans = 0x7fffffffd850, path = 0x555556da8000, update_path = 0x0, key_cache_path = 0x0, 
          btree_id = BTREE_ID_extents, min_depth = 0, advanced = 0, flags = 2056, snapshot = 0, pos = {
            snapshot = 4294967295, offset = 4101, inode = 4098}, k = {u64s = 7 '\a', format = 1 '\001', 
            needs_whiteout = 1 '\001', type = 6 '\006', pad = "", version = {lo = 0, hi = 0}, size = 21, p = {
              snapshot = 4294967295, offset = 4101, inode = 4098}}, journal_idx = 0, journal_pos = {snapshot = 0, 
            offset = 0, inode = 0}}
        k = <optimized out>
        extent_ends = {nr = 124, size = 128, data = 0x555556dba000}
        res = {sectors = 0, gen = 0, nr_replicas = 0}
        ret = 0
        __func__ = "check_extents"
#17 0x0000555555661871 in bch2_fsck_full (c=c@entry=0x7ffff797f000) at libbcachefs/fsck.c:2435
        ret = 0
#18 0x0000555555610b8a in bch2_fs_recovery (c=0x7ffff797f000) at libbcachefs/recovery.c:1439
        err = 0x555555846c56 "error in fsck"
        clean = <optimized out>
        last_journal_entry = <optimized out>
        last_seq = 8508556
        blacklist_seq = 8508557
        journal_seq = 8508565
        write_sb = false
        ret = <optimized out>
        __func__ = "bch2_fs_recovery"
#19 0x000055555562496d in bch2_fs_start (c=c@entry=0x7ffff797f000) at libbcachefs/super.c:934
        mi = 0x555555a752f0
        ca = <optimized out>
        now = <optimized out>
        i = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "bch2_fs_start"
#20 0x0000555555627567 in bch2_fs_open (devices=devices@entry=0x7fffffffe3a8, nr_devices=<optimized out>, 
    nr_devices@entry=1, opts=...) at libbcachefs/super.c:1924
        sb = <optimized out>
        c = 0x7ffff797f000
        mi = <optimized out>
        i = <optimized out>
        best_sb = <optimized out>
        errbuf = {buf = 0x0, size = 0, pos = 0, last_newline = 0, last_field = 0, indent = 0, atomic = 0 '\000', 
          allocation_failure = false, heap_allocated = true, si_units = PRINTBUF_UNITS_2, human_readable_units = false, 
          has_indent_or_tabstops = false, suppress_indent_tabstop_handling = false, nr_tabstops = 0 '\000', 
          cur_tabstop = 0 '\000', _tabstops = "\000\000\000\000\000"}
        ret = <optimized out>
        __func__ = "bch2_fs_open"
#21 0x00005555555a36d3 in cmd_fsck (argc=1, argv=0x7fffffffe3a8, argv@entry=0x7fffffffe398) at cmd_fsck.c:96
        longopts = {{name = 0x5555558383f0 "ratelimit_errors", has_arg = 0, flag = 0x0, val = 114}, {
            name = 0x555555838401 "reconstruct_alloc", has_arg = 0, flag = 0x0, val = 82}, {name = 0x55555583568a "help", 
            has_arg = 0, flag = 0x0, val = 104}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        opts = {block_size_defined = 0, btree_node_size_defined = 0, errors_defined = 0, metadata_replicas_defined = 0, 
          data_replicas_defined = 0, metadata_replicas_required_defined = 0, data_replicas_required_defined = 0, 
          encoded_extent_max_defined = 0, metadata_checksum_defined = 0, data_checksum_defined = 0, compression_defined = 0, 
          background_compression_defined = 0, str_hash_defined = 0, metadata_target_defined = 0, 
          foreground_target_defined = 0, background_target_defined = 0, promote_target_defined = 0, 
          erasure_code_defined = 0, inodes_32bit_defined = 0, shard_inode_numbers_defined = 0, 
          inodes_use_key_cache_defined = 0, btree_node_mem_ptr_optimization_defined = 0, 
          btree_write_buffer_size_defined = 0, gc_reserve_percent_defined = 0, gc_reserve_bytes_defined = 0, 
          root_reserve_percent_defined = 0, wide_macs_defined = 0, inline_data_defined = 0, acl_defined = 0, 
          usrquota_defined = 0, grpquota_defined = 0, prjquota_defined = 0, degraded_defined = 1, very_degraded_defined = 0, 
          discard_defined = 0, verbose_defined = 0, journal_flush_delay_defined = 0, journal_flush_disabled_defined = 0, 
          journal_reclaim_delay_defined = 0, move_bytes_in_flight_defined = 0, move_ios_in_flight_defined = 0, 
          fsck_defined = 1, fix_errors_defined = 1, ratelimit_errors_defined = 0, nochanges_defined = 0, 
          norecovery_defined = 0, keep_journal_defined = 0, read_entire_journal_defined = 0, read_journal_only_defined = 0, 
          journal_transaction_names_defined = 0, noexcl_defined = 0, direct_io_defined = 0, sb_defined = 0, 
          read_only_defined = 0, nostart_defined = 0, reconstruct_alloc_defined = 0, version_upgrade_defined = 0, 
          buckets_nouse_defined = 0, project_defined = 0, nocow_defined = 0, nocow_enabled_defined = 0, 
          no_data_io_defined = 0, fs_size_defined = 0, bucket_defined = 0, durability_defined = 0, block_size = 0, 
          btree_node_size = 0, errors = 0 '\000', metadata_replicas = 0 '\000', data_replicas = 0 '\000', 
          metadata_replicas_required = 0 '\000', data_replicas_required = 0 '\000', encoded_extent_max = 0, 
          metadata_checksum = 0 '\000', data_checksum = 0 '\000', compression = 0 '\000', background_compression = 0 '\000', 
          str_hash = 0 '\000', metadata_target = 0, foreground_target = 0, background_target = 0, promote_target = 0, 
          erasure_code = 0, inodes_32bit = 0 '\000', shard_inode_numbers = 0 '\000', inodes_use_key_cache = 0 '\000', 
          btree_node_mem_ptr_optimization = 0 '\000', btree_write_buffer_size = 0, gc_reserve_percent = 0 '\000', 
          gc_reserve_bytes = 0, root_reserve_percent = 0 '\000', wide_macs = 0 '\000', inline_data = 0 '\000', 
          acl = 0 '\000', usrquota = 0 '\000', grpquota = 0 '\000', prjquota = 0 '\000', degraded = 1 '\001', 
          very_degraded = 0 '\000', discard = 0 '\000', verbose = 0 '\000', journal_flush_delay = 0, 
--Type <RET> for more, q to quit, c to continue without paging--
          journal_flush_disabled = 0 '\000', journal_reclaim_delay = 0, move_bytes_in_flight = 0, move_ios_in_flight = 0, 
          fsck = 1 '\001', fix_errors = 1 '\001', ratelimit_errors = 0 '\000', nochanges = 0 '\000', norecovery = 0 '\000', 
          keep_journal = 0 '\000', read_entire_journal = 0 '\000', read_journal_only = 0 '\000', 
          journal_transaction_names = 0 '\000', noexcl = 0 '\000', direct_io = 0 '\000', sb = 0, read_only = 0 '\000', 
          nostart = 0 '\000', reconstruct_alloc = 0 '\000', version_upgrade = 0 '\000', buckets_nouse = 0 '\000', 
          project = 0 '\000', nocow = 0 '\000', nocow_enabled = 0 '\000', no_data_io = 0 '\000', fs_size = 0, bucket = 0, 
          durability = 0 '\000'}
        i = 1
        opt = <optimized out>
        ret = 0
        c = <optimized out>
#22 0x0000555555599da9 in main (argc=<optimized out>, argv=0x7fffffffe398) at bcachefs.c:205
        cmd = 0x7fffffffe64d "fsck"
(gdb) 
```

**Comment by koverstreet** [comment]
Fix pushed - please reopen if needed
