### ISSUE TITLE
bcachefs: libbcachefs/extents.h:71: extent_entry_bytes: Assertion `0' failed.

### ISSUE THREAD

**Issue by rubiksdot** [koverstreet/bcachefs#641]
```sh
$ bcachefs fsck /dev/tmp/tmptmp
mounting version 1.3: rebalance_work opts=metadata_checksum=crc64,data_checksum=crc64,background_compression=gzip:9,degraded,fsck,fix_errors=ask
recovering from clean shutdown, journal seq 2451986
journal read done, replaying entries 2451986-2451986
alloc_read... done
stripes_read... done
snapshots_read... done
check_allocations... done
journal_replay... done
check_alloc_info... done
check_lrus... done
check_btree_backpointers... done
check_backpointers_to_extents... done
check_extents_to_backpointers...bcachefs: libbcachefs/extents.h:71: extent_entry_bytes: Assertion `0' failed.
Aborted
```

Nothing in dmesg.
Background compression, if it matters, was lz4 before I changed it to gzip:9.
Fsck was done on a mounted r/o filesystem.
Linux 6.7.0
bcachefs-tools 1.3.3

```sh
$ df /media/hds/
Filesystem              1K-blocks       Used Available Use% Mounted on
/dev/mapper/tmp-tmptmp 1971487068 1915604308  55023024  98% /media/hds
$ df -i /media/hds/
Filesystem                Inodes    IUsed     IFree IUse% Mounted on
/dev/mapper/tmp-tmptmp 984897404 90773236 894124168   10% /media/hds
```

**Comment by koverstreet** [comment]
Can you run it under kasan, and gdb, and see if they turn up anything?

Alternately, hop on IRC (irc.oftc.net#bcachef) and send me a metadata dump of your filesystem (bcachefs dump; magic wormhole)

**Comment by rubiksdot** [comment]
So far:

```gdb
#0  0x00005555555804e2 in __ffs (word=<error reading variable: Cannot access memory at address 0x7fffbacbb688>) at include/linux/bitops.h:263
No locals.
#1  extent_entry_type (e=<optimized out>) at libbcachefs/extents.h:55
        ret = <optimized out>
#2  extent_entry_bytes (entry=0x7fffbacbb688) at libbcachefs/extents.h:64
        __PRETTY_FUNCTION__ = "extent_entry_bytes"
#3  check_extent_to_backpointers (trans=trans@entry=0x555555fca000, btree=btree@entry=BTREE_ID_dirents, level=level@entry=1, bucket_start=..., bucket_end=..., 
    last_flushed=last_flushed@entry=0x7fffffffd720, k=...) at libbcachefs/backpointers.c:473
        c = 0x7ffff7b2d000
        ptrs = {start = <optimized out>, end = 0x7fffbacbb690}
        entry = 0x7fffbacbb688
        p = {idx = 0, has_ec = <optimized out>, crc = {compressed_size = 0, uncompressed_size = 0, live_size = <optimized out>, csum_type = <optimized out>, 
            compression_type = <optimized out>, offset = <optimized out>, nonce = <optimized out>, csum = {lo = <optimized out>, hi = <optimized out>}}, ptr = {type = <optimized out>, 
            cached = <optimized out>, unused = <optimized out>, unwritten = <optimized out>, offset = <optimized out>, dev = <optimized out>, gen = <optimized out>}, ec = {
            type = <optimized out>, block = <optimized out>, redundancy = <optimized out>, idx = <optimized out>}}
        ret = <optimized out>
#4  0x00005555555823fc in bch2_check_extents_to_backpointers_pass (bucket_end=..., bucket_start=..., trans=0x555555fca000) at libbcachefs/backpointers.c:622
        _restart_count = 0
        _ret2 = <optimized out>
        level = 1
        depth = 1
        c = 0x7ffff7b2d000
        iter = {trans = 0x555555fca000, path = 0x555555fca2c8, update_path = 0x0, key_cache_path = 0x0, btree_id = BTREE_ID_dirents, min_depth = 1, advanced = 0, flags = 1556, snapshot = 0, 
          pos = {snapshot = 4294967295, offset = 6978986067668604157, inode = 1074960193}, k = {u64s = 11 '\v', format = 1 '\001', needs_whiteout = 1 '\001', type = 18 '\022', pad = "", 
            version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 4294967295, offset = 6978986067668604157, inode = 1074960193}}, journal_idx = 0, journal_pos = {snapshot = 0, offset = 0, 
            inode = 0}}
        btree_id = BTREE_ID_dirents
        k = <optimized out>
        last_flushed = {level = 4294967295, pos = {snapshot = 0, offset = 0, inode = 0}}
        ret = <optimized out>
        c = <optimized out>
        iter = <optimized out>
        btree_id = <optimized out>
        k = <optimized out>
        last_flushed = <optimized out>
        ret = <optimized out>
        level = <optimized out>
        depth = <optimized out>
        _restart_count = <optimized out>
        _ret2 = <optimized out>
        _restart_count = <optimized out>
        _ret2 = <optimized out>
#5  bch2_check_extents_to_backpointers (c=<optimized out>) at libbcachefs/backpointers.c:729
        trans = 0x555555fca000
        __func__ = "bch2_check_extents_to_backpointers"
        start = <optimized out>
        end = <optimized out>
        ret = 0
#6  0x0000555555621cb3 in bch2_run_recovery_pass (pass=<optimized out>, c=0x7ffff7b2d000) at libbcachefs/recovery.c:661
        p = 0x5555556bfc40 <recovery_pass_fns+224>
        ret = <optimized out>
        ret = <optimized out>
        p = <optimized out>
#7  bch2_run_recovery_passes (c=<optimized out>) at libbcachefs/recovery.c:678
        ret = 0
        ret = <optimized out>
#8  bch2_fs_recovery (c=0x7ffff7b2d000) at libbcachefs/recovery.c:872
        clean = 0x555555919800
        last_journal_entry = <optimized out>
        last_seq = 2451986
        blacklist_seq = 2451987
        journal_seq = 2451987
        write_sb = false
        ret = 0
        __func__ = "bch2_fs_recovery"
#9  0x000055555563c165 in bch2_fs_start (c=c@entry=0x7ffff7b2d000) at libbcachefs/super.c:966
        ca = 0x0
        now = <optimized out>
        i = 1
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "bch2_fs_start"
        __func__ = "bch2_fs_start"
#10 0x000055555563f1bd in bch2_fs_open (devices=devices@entry=0x7fffffffdfd0, nr_devices=nr_devices@entry=1, opts=...) at libbcachefs/super.c:1956
        sbs = {nr = 1, size = 1, data = 0x5555557c74c0}
        c = 0x7ffff7b2d000
        sb = <optimized out>
        best = <optimized out>
        errbuf = {buf = 0x0, size = 0, pos = 0, last_newline = 0, last_field = 0, indent = 0, atomic = 0 '\000', allocation_failure = false, heap_allocated = true, 
          si_units = PRINTBUF_UNITS_2, human_readable_units = false, has_indent_or_tabstops = false, suppress_indent_tabstop_handling = false, nr_tabstops = 0 '\000', 
          cur_tabstop = 0 '\000', _tabstops = "\000\000\000\000\000"}
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "bch2_fs_open"
        __func__ = "bch2_fs_open"
#11 0x000055555556a2a9 in cmd_fsck (argc=1, argv=0x7fffffffdfd0, argv@entry=0x7fffffffdfc8) at ./cmd_fsck.c:94
        longopts = {{name = 0x55555565e23e "ratelimit_errors", has_arg = 0, flag = 0x0, val = 114}, {name = 0x55555565e24f "reconstruct_alloc", has_arg = 0, flag = 0x0, val = 82}, {
            name = 0x55555565b0e6 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        opts = {block_size_defined = 0, btree_node_size_defined = 0, errors_defined = 0, metadata_replicas_defined = 0, data_replicas_defined = 0, metadata_replicas_required_defined = 0, 
          data_replicas_required_defined = 0, encoded_extent_max_defined = 0, metadata_checksum_defined = 0, data_checksum_defined = 0, compression_defined = 0, 
          background_compression_defined = 0, str_hash_defined = 0, metadata_target_defined = 0, foreground_target_defined = 0, background_target_defined = 0, promote_target_defined = 0, 
          erasure_code_defined = 0, inodes_32bit_defined = 0, shard_inode_numbers_defined = 0, inodes_use_key_cache_defined = 0, btree_node_mem_ptr_optimization_defined = 0, 
          btree_write_buffer_size_defined = 0, gc_reserve_percent_defined = 0, gc_reserve_bytes_defined = 0, root_reserve_percent_defined = 0, wide_macs_defined = 0, 
          inline_data_defined = 0, acl_defined = 0, usrquota_defined = 0, grpquota_defined = 0, prjquota_defined = 0, degraded_defined = 1, very_degraded_defined = 0, discard_defined = 0, 
          verbose_defined = 0, journal_flush_delay_defined = 0, journal_flush_disabled_defined = 0, journal_reclaim_delay_defined = 0, move_bytes_in_flight_defined = 0, 
          move_ios_in_flight_defined = 0, fsck_defined = 1, fix_errors_defined = 1, ratelimit_errors_defined = 0, nochanges_defined = 0, norecovery_defined = 0, keep_journal_defined = 0, 
          read_entire_journal_defined = 0, read_journal_only_defined = 0, journal_transaction_names_defined = 0, noexcl_defined = 0, direct_io_defined = 0, sb_defined = 0, 
          read_only_defined = 0, nostart_defined = 0, reconstruct_alloc_defined = 0, version_upgrade_defined = 0, buckets_nouse_defined = 0, project_defined = 0, nocow_defined = 0, 
          nocow_enabled_defined = 0, no_data_io_defined = 0, fs_size_defined = 0, bucket_defined = 0, durability_defined = 0, block_size = 0, btree_node_size = 0, errors = 0 '\000', 
          metadata_replicas = 0 '\000', data_replicas = 0 '\000', metadata_replicas_required = 0 '\000', data_replicas_required = 0 '\000', encoded_extent_max = 0, 
          metadata_checksum = 0 '\000', data_checksum = 0 '\000', compression = 0 '\000', background_compression = 0 '\000', str_hash = 0 '\000', metadata_target = 0, foreground_target = 0, 
          background_target = 0, promote_target = 0, erasure_code = 0, inodes_32bit = 0 '\000', shard_inode_numbers = 0 '\000', inodes_use_key_cache = 0 '\000', 
          btree_node_mem_ptr_optimization = 0 '\000', btree_write_buffer_size = 0, gc_reserve_percent = 0 '\000', gc_reserve_bytes = 0, root_reserve_percent = 0 '\000', 
          wide_macs = 0 '\000', inline_data = 0 '\000', acl = 0 '\000', usrquota = 0 '\000', grpquota = 0 '\000', prjquota = 0 '\000', degraded = 1 '\001', very_degraded = 0 '\000', 
          discard = 0 '\000', verbose = 0 '\000', journal_flush_delay = 0, journal_flush_disabled = 0 '\000', journal_reclaim_delay = 0, move_bytes_in_flight = 0, move_ios_in_flight = 0, 
          fsck = 1 '\001', fix_errors = 3 '\003', ratelimit_errors = 0 '\000', nochanges = 0 '\000', norecovery = 0 '\000', keep_journal = 0 '\000', read_entire_journal = 0 '\000', 
          read_journal_only = 0 '\000', journal_transaction_names = 0 '\000', noexcl = 0 '\000', direct_io = 0 '\000', sb = 0, read_only = 0 '\000', nostart = 0 '\000', 
          reconstruct_alloc = 0 '\000', version_upgrade = 0 '\000', buckets_nouse = 0 '\000', project = 0 '\000', nocow = 0 '\000', nocow_enabled = 0 '\000', no_data_io = 0 '\000', 
          fs_size = 0, bucket = 0, durability = 0 '\000'}
        i = 1
        opt = <optimized out>
        ret = 2
        c = <optimized out>
#12 0x0000555555562e0c in main (argc=<optimized out>, argv=0x7fffffffdfc8) at ./bcachefs.c:232
        cmd = <optimized out>
```

**Comment by rubiksdot** [comment]
Saw the optimised out stuff so am re-running with -O0 bcachefs-tools. It takes a few hours for the fsck so am getting started on it now.

**Comment by rubiksdot** [comment]
A few hours later...

short:
```gdb
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7c89d9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7c3af32 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7c25472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7c25395 in __assert_fail_base (fmt=0x7ffff7d99a90 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x555555708005 "0",
    file=file@entry=0x55555570801b "libbcachefs/extents.h", line=line@entry=71, function=function@entry=0x5555557084c0 <__PRETTY_FUNCTION__.14> "extent_entry_bytes") at ./assert/assert.c:92
#5  0x00007ffff7c33e32 in __GI___assert_fail (assertion=0x555555708005 "0", file=0x55555570801b "libbcachefs/extents.h", line=71,
    function=0x5555557084c0 <__PRETTY_FUNCTION__.14> "extent_entry_bytes") at ./assert/assert.c:101
#6  0x000055555558c461 in extent_entry_bytes (entry=0x7fffd880a658) at libbcachefs/extents.h:71
#7  0x000055555558fe49 in check_extent_to_backpointers (trans=0x55556987b000, btree=BTREE_ID_extents, level=0, bucket_start=..., bucket_end=..., last_flushed=0x7fffffffd640, k=...)
    at libbcachefs/backpointers.c:473
#8  0x0000555555590701 in bch2_check_extents_to_backpointers_pass (trans=0x55556987b000, bucket_start=..., bucket_end=...) at libbcachefs/backpointers.c:622
#9  0x00005555555913e7 in bch2_check_extents_to_backpointers (c=0x7ffff7b2d000) at libbcachefs/backpointers.c:729
#10 0x0000555555686be1 in bch2_run_recovery_pass (c=0x7ffff7b2d000, pass=BCH_RECOVERY_PASS_check_extents_to_backpointers) at libbcachefs/recovery.c:661
#11 0x0000555555686c6c in bch2_run_recovery_passes (c=0x7ffff7b2d000) at libbcachefs/recovery.c:678
#12 0x0000555555687507 in bch2_fs_recovery (c=0x7ffff7b2d000) at libbcachefs/recovery.c:872
#13 0x00005555556ab5dc in bch2_fs_start (c=0x7ffff7b2d000) at libbcachefs/super.c:966
#14 0x00005555556ae6bd in bch2_fs_open (devices=0x7fffffffdfb0, nr_devices=1, opts=...) at libbcachefs/super.c:1956
#15 0x000055555556ca65 in cmd_fsck (argc=1, argv=0x7fffffffdfb0) at cmd_fsck.c:94
#16 0x00005555555644e6 in main (argc=2, argv=0x7fffffffdfa8) at bcachefs.c:232
```

full:
```gdb
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {140737354125344}}
        ret = <optimized out>
#1  0x00007ffff7c89d9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
No locals.
#2  0x00007ffff7c3af32 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007ffff7c25472 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {71, 93824996213104, 113, 140737351851104, 110, 47244640269, 0, 140737488343976, 
              4953142904336049664, 5, 18446744073709550408, 11, 93824994017307, 71, 93824994017285, 140737354125344}}, sa_flags = -137790049, sa_restorer = 0x7ffff7d9647c <_nl_C_name>}
#4  0x00007ffff7c25395 in __assert_fail_base (fmt=0x7ffff7d99a90 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x555555708005 "0", 
    file=file@entry=0x55555570801b "libbcachefs/extents.h", line=line@entry=71, function=function@entry=0x5555557084c0 <__PRETTY_FUNCTION__.14> "extent_entry_bytes") at ./assert/assert.c:92
        str = 0x555555920170 " ", <incomplete sequence \307>
        total = 4096
#5  0x00007ffff7c33e32 in __GI___assert_fail (assertion=0x555555708005 "0", file=0x55555570801b "libbcachefs/extents.h", line=71, 
    function=0x5555557084c0 <__PRETTY_FUNCTION__.14> "extent_entry_bytes") at ./assert/assert.c:101
No locals.
#6  0x000055555558c461 in extent_entry_bytes (entry=0x7fffd880a658) at libbcachefs/extents.h:71
        __PRETTY_FUNCTION__ = "extent_entry_bytes"
#7  0x000055555558fe49 in check_extent_to_backpointers (trans=0x55556987b000, btree=BTREE_ID_extents, level=0, bucket_start=..., bucket_end=..., last_flushed=0x7fffffffd640, k=...)
    at libbcachefs/backpointers.c:473
        c = 0x7ffff7b2d000
        ptrs = {start = 0x7fffd880a648, end = 0x7fffd880a660}
        entry = 0x7fffd880a658
        p = {idx = 0, has_ec = false, crc = {compressed_size = 56, uncompressed_size = 104, live_size = 104, csum_type = 6 '\006', compression_type = 3 '\003', offset = 0, nonce = 0, 
            csum = {lo = 12019232227582871641, hi = 0}}, ptr = {type = 1, cached = 0, unused = 0, unwritten = 0, offset = 179133440, dev = 0, gen = 1}, ec = {type = 1, block = 13, 
            redundancy = 0, idx = 715827886}}
        ret = 0
#8  0x0000555555590701 in bch2_check_extents_to_backpointers_pass (trans=0x55556987b000, bucket_start=..., bucket_end=...) at libbcachefs/backpointers.c:622
        _restart_count = 337797
        _ret2 = 0
        level = 0
        depth = 0
        c = 0x7ffff7b2d000
        iter = {trans = 0x55556987b000, path = 0x55556987b1b8, update_path = 0x0, key_cache_path = 0x0, btree_id = BTREE_ID_extents, min_depth = 0, advanced = 0, flags = 1556, snapshot = 0, 
          pos = {snapshot = 4294967295, offset = 9156168, inode = 5420}, k = {u64s = 8 '\b', format = 1 '\001', needs_whiteout = 1 '\001', type = 6 '\006', pad = "", version = {lo = 0, 
              hi = 0}, size = 104, p = {snapshot = 4294967295, offset = 9156168, inode = 5420}}, journal_idx = 0, journal_pos = {snapshot = 0, offset = 0, inode = 0}}
        btree_id = BTREE_ID_extents
        k = {k = 0x7fffffffd6b0, v = 0x7fffd880a648}
        last_flushed = {level = 4294967295, pos = {snapshot = 0, offset = 0, inode = 0}}
        ret = 0
#9  0x00005555555913e7 in bch2_check_extents_to_backpointers (c=0x7ffff7b2d000) at libbcachefs/backpointers.c:729
        trans = 0x55556987b000
        __func__ = "bch2_check_extents_to_backpointers"
        start = {snapshot = 0, offset = 0, inode = 0}
        end = {snapshot = 0, offset = 2354575, inode = 0}
        ret = 0
#10 0x0000555555686be1 in bch2_run_recovery_pass (c=0x7ffff7b2d000, pass=BCH_RECOVERY_PASS_check_extents_to_backpointers) at libbcachefs/recovery.c:661
        p = 0x555555813680 <recovery_pass_fns+224>
        ret = 0
#11 0x0000555555686c6c in bch2_run_recovery_passes (c=0x7ffff7b2d000) at libbcachefs/recovery.c:678
        ret = 0
#12 0x0000555555687507 in bch2_fs_recovery (c=0x7ffff7b2d000) at libbcachefs/recovery.c:872
        clean = 0x555555a6b800
        last_journal_entry = 0x7fffe0103068
        last_seq = 2451986
        blacklist_seq = 2451987
        journal_seq = 2451987
        write_sb = false
        ret = 0
        __func__ = "bch2_fs_recovery"
#13 0x00005555556ab5dc in bch2_fs_start (c=0x7ffff7b2d000) at libbcachefs/super.c:966
        ca = 0x0
        now = 1706328425
        i = 1
        ret = 0
        __PRETTY_FUNCTION__ = "bch2_fs_start"
        __func__ = "bch2_fs_start"
#14 0x00005555556ae6bd in bch2_fs_open (devices=0x7fffffffdfb0, nr_devices=1, opts=...) at libbcachefs/super.c:1956
        sbs = {nr = 1, size = 1, data = 0x5555559194a0}
        c = 0x7ffff7b2d000
        sb = 0x5555559194d8
        best = 0x5555559194a0
        errbuf = {buf = 0x0, size = 0, pos = 0, last_newline = 0, last_field = 0, indent = 0, atomic = 0 '\000', allocation_failure = false, heap_allocated = true, 
          si_units = PRINTBUF_UNITS_2, human_readable_units = false, has_indent_or_tabstops = false, suppress_indent_tabstop_handling = false, nr_tabstops = 0 '\000', 
          cur_tabstop = 0 '\000', _tabstops = "\000\000\000\000\000"}
        ret = 0
        __PRETTY_FUNCTION__ = "bch2_fs_open"
        __func__ = "bch2_fs_open"
#15 0x000055555556ca65 in cmd_fsck (argc=1, argv=0x7fffffffdfb0) at cmd_fsck.c:94
        longopts = {{name = 0x5555556ef3e4 "ratelimit_errors", has_arg = 0, flag = 0x0, val = 114}, {name = 0x5555556ef3f5 "reconstruct_alloc", has_arg = 0, flag = 0x0, val = 82}, {
            name = 0x5555556ef407 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        opts = {block_size_defined = 0, btree_node_size_defined = 0, errors_defined = 0, metadata_replicas_defined = 0, data_replicas_defined = 0, metadata_replicas_required_defined = 0, 
          data_replicas_required_defined = 0, encoded_extent_max_defined = 0, metadata_checksum_defined = 0, data_checksum_defined = 0, compression_defined = 0, 
          background_compression_defined = 0, str_hash_defined = 0, metadata_target_defined = 0, foreground_target_defined = 0, background_target_defined = 0, promote_target_defined = 0, 
          erasure_code_defined = 0, inodes_32bit_defined = 0, shard_inode_numbers_defined = 0, inodes_use_key_cache_defined = 0, btree_node_mem_ptr_optimization_defined = 0, 
          btree_write_buffer_size_defined = 0, gc_reserve_percent_defined = 0, gc_reserve_bytes_defined = 0, root_reserve_percent_defined = 0, wide_macs_defined = 0, 
          inline_data_defined = 0, acl_defined = 0, usrquota_defined = 0, grpquota_defined = 0, prjquota_defined = 0, degraded_defined = 1, very_degraded_defined = 0, discard_defined = 0, 
          verbose_defined = 0, journal_flush_delay_defined = 0, journal_flush_disabled_defined = 0, journal_reclaim_delay_defined = 0, move_bytes_in_flight_defined = 0, 
          move_ios_in_flight_defined = 0, fsck_defined = 1, fix_errors_defined = 1, ratelimit_errors_defined = 0, nochanges_defined = 0, norecovery_defined = 0, keep_journal_defined = 0, 
          read_entire_journal_defined = 0, read_journal_only_defined = 0, journal_transaction_names_defined = 0, noexcl_defined = 0, direct_io_defined = 0, sb_defined = 0, 
          read_only_defined = 0, nostart_defined = 0, reconstruct_alloc_defined = 0, version_upgrade_defined = 0, buckets_nouse_defined = 0, project_defined = 0, nocow_defined = 0, 
          nocow_enabled_defined = 0, no_data_io_defined = 0, fs_size_defined = 0, bucket_defined = 0, durability_defined = 0, block_size = 0, btree_node_size = 0, errors = 0 '\000', 
          metadata_replicas = 0 '\000', data_replicas = 0 '\000', metadata_replicas_required = 0 '\000', data_replicas_required = 0 '\000', encoded_extent_max = 0, 
          metadata_checksum = 0 '\000', data_checksum = 0 '\000', compression = 0 '\000', background_compression = 0 '\000', str_hash = 0 '\000', metadata_target = 0, foreground_target = 0, 
          background_target = 0, promote_target = 0, erasure_code = 0, inodes_32bit = 0 '\000', shard_inode_numbers = 0 '\000', inodes_use_key_cache = 0 '\000', 
          btree_node_mem_ptr_optimization = 0 '\000', btree_write_buffer_size = 0, gc_reserve_percent = 0 '\000', gc_reserve_bytes = 0, root_reserve_percent = 0 '\000', 
          wide_macs = 0 '\000', inline_data = 0 '\000', acl = 0 '\000', usrquota = 0 '\000', grpquota = 0 '\000', prjquota = 0 '\000', degraded = 1 '\001', very_degraded = 0 '\000', 
          discard = 0 '\000', verbose = 0 '\000', journal_flush_delay = 0, journal_flush_disabled = 0 '\000', journal_reclaim_delay = 0, move_bytes_in_flight = 0, move_ios_in_flight = 0, 
          fsck = 1 '\001', fix_errors = 3 '\003', ratelimit_errors = 0 '\000', nochanges = 0 '\000', norecovery = 0 '\000', keep_journal = 0 '\000', read_entire_journal = 0 '\000', 
          read_journal_only = 0 '\000', journal_transaction_names = 0 '\000', noexcl = 0 '\000', direct_io = 0 '\000', sb = 0, read_only = 0 '\000', nostart = 0 '\000', 
          reconstruct_alloc = 0 '\000', version_upgrade = 0 '\000', buckets_nouse = 0 '\000', project = 0 '\000', nocow = 0 '\000', nocow_enabled = 0 '\000', no_data_io = 0 '\000', 
          fs_size = 0, bucket = 0, durability = 0 '\000'}
        i = 1
        opt = -1
        ret = 2
        c = 0x555555563f62 <pop_cmd+131>
#16 0x00005555555644e6 in main (argc=2, argv=0x7fffffffdfa8) at bcachefs.c:232
        cmd = 0x7fffffffe26e "fsck"
```

Holding gdb open in case you need something other than a backtrace.

**Comment by koverstreet** [comment]
yeah, that doesn't give me enough unfortunately.

Does bcachefs dump work for you?

**Comment by rubiksdot** [comment]
Yeah but I can't release the result. There is ssh and ssl key content in there at least. :(
