### ISSUE TITLE
1.12: rebalance_work_acct_fix - "bcachefs format" hangs when not using encryption

### ISSUE THREAD

**Issue by nitinkmr333** [koverstreet/bcachefs#738]
**Description**:
Shell hangs when trying to format a drive with bcachefs version _1.12: rebalance_work_acct_fix_.
This does not happen on previous version _1.11: disk_accounting_inum_.

Command used-
```bash
sudo bcachefs format /dev/sda1
```
Output-
```bash
❯ sudo bcachefs format /dev/sda1
External UUID:                             fa32ad61-14d8-4b61-b299-34e20591474c
Internal UUID:                             73ed6d61-90da-4ae2-9d4f-88f851712391
Magic number:                              c68573f6-66ce-90a9-d96a-60cf803df7ef
Device index:                              0
Label:                                     (none)
Version:                                   1.12: rebalance_work_acct_fix
Version upgrade complete:                  0.0: (unknown version)
Oldest version on disk:                    1.12: rebalance_work_acct_fix
Created:                                   Sun Sep  1 12:38:51 2024
Sequence number:                           0
Time of last write:                        Thu Jan  1 05:30:00 1970
Superblock size:                           976 B/1.00 MiB
Clean:                                     0
Devices:                                   1
Sections:                                  members_v1,members_v2
Features:                                  new_siphash,new_extent_overwrite,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                           

Options:
  block_size:                              512 B
  btree_node_size:                         256 KiB
  errors:                                  continue [fix_safe] panic ro 
  metadata_replicas:                       1
  data_replicas:                           1
  metadata_replicas_required:              1
  data_replicas_required:                  1
  encoded_extent_max:                      64.0 KiB
  metadata_checksum:                       none [crc32c] crc64 xxhash 
  data_checksum:                           none [crc32c] crc64 xxhash 
  compression:                             none
  background_compression:                  none
  str_hash:                                crc32c crc64 [siphash] 
  metadata_target:                         none
  foreground_target:                       none
  background_target:                       none
  promote_target:                          none
  erasure_code:                            0
  inodes_32bit:                            1
  shard_inode_numbers:                     1
  inodes_use_key_cache:                    1
  gc_reserve_percent:                      8
  gc_reserve_bytes:                        0 B
  root_reserve_percent:                    0
  wide_macs:                               0
  promote_whole_extents:                   1
  acl:                                     1
  usrquota:                                0
  grpquota:                                0
  prjquota:                                0
  journal_flush_delay:                     1000
  journal_flush_disabled:                  0
  journal_reclaim_delay:                   100
  journal_transaction_names:               1
  allocator_stuck_timeout:                 30
  version_upgrade:                         [compatible] incompatible none 
  nocow:                                   0

members_v2 (size 160):
Device:                                    0
  Label:                                   (none)
  UUID:                                    60a86a0e-8f3c-4dd9-90f7-07cfb57ebc2f
  Size:                                    931 GiB
  read errors:                             0
  write errors:                            0
  checksum errors:                         0
  seqread iops:                            0
  seqwrite iops:                           0
  randread iops:                           0
  randwrite iops:                          0
  Bucket size:                             512 KiB
  First bucket:                            0
  Buckets:                                 1907670
  Last mount:                              (never)
  Last superblock write:                   0
  State:                                   rw
  Data allowed:                            journal,btree,user
  Has data:                                (none)
  Btree allocated bitmap blocksize:        1.00 B
  Btree allocated bitmap:                  0000000000000000000000000000000000000000000000000000000000000000
  Durability:                              1
  Discard:                                 0
  Freespace initialized:                   0
starting version 1.12: rebalance_work_acct_fix
initializing new filesystem
going read-write

```
The shell hangs at "going read-write". However, if I press `ctrl+c` and mount the drive, the drives mounts fine. It looks like it might just be a visual bug and succeeding steps run fine in the background.

This does not happen if I use "--encrypted" flag-
```bash
❯ sudo bcachefs format --encrypted /dev/sda1
Enter passphrase: 
Enter same passphrase again: 
External UUID:                             bcb59fee-5eac-4d5f-b59b-caa3b74f4d9e
Internal UUID:                             d06b1a51-23d0-44b2-8df0-bc4b096f84a0
Magic number:                              c68573f6-66ce-90a9-d96a-60cf803df7ef
Device index:                              0
Label:                                     (none)
Version:                                   1.12: rebalance_work_acct_fix
Version upgrade complete:                  0.0: (unknown version)
Oldest version on disk:                    1.12: rebalance_work_acct_fix
Created:                                   Sun Sep  1 12:47:07 2024
Sequence number:                           0
Time of last write:                        Thu Jan  1 05:30:00 1970
Superblock size:                           1.02 KiB/1.00 MiB
Clean:                                     0
Devices:                                   1
Sections:                                  members_v1,crypt,members_v2
Features:                                  new_siphash,new_extent_overwrite,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                           

Options:
  block_size:                              512 B
  btree_node_size:                         256 KiB
  errors:                                  continue [fix_safe] panic ro 
  metadata_replicas:                       1
  data_replicas:                           1
  metadata_replicas_required:              1
  data_replicas_required:                  1
  encoded_extent_max:                      64.0 KiB
  metadata_checksum:                       none [crc32c] crc64 xxhash 
  data_checksum:                           none [crc32c] crc64 xxhash 
  compression:                             none
  background_compression:                  none
  str_hash:                                crc32c crc64 [siphash] 
  metadata_target:                         none
  foreground_target:                       none
  background_target:                       none
  promote_target:                          none
  erasure_code:                            0
  inodes_32bit:                            1
  shard_inode_numbers:                     1
  inodes_use_key_cache:                    1
  gc_reserve_percent:                      8
  gc_reserve_bytes:                        0 B
  root_reserve_percent:                    0
  wide_macs:                               0
  promote_whole_extents:                   1
  acl:                                     1
  usrquota:                                0
  grpquota:                                0
  prjquota:                                0
  journal_flush_delay:                     1000
  journal_flush_disabled:                  0
  journal_reclaim_delay:                   100
  journal_transaction_names:               1
  allocator_stuck_timeout:                 30
  version_upgrade:                         [compatible] incompatible none 
  nocow:                                   0

members_v2 (size 160):
Device:                                    0
  Label:                                   (none)
  UUID:                                    0eca519c-420e-4495-8b01-b6bd08f2bdf1
  Size:                                    931 GiB
  read errors:                             0
  write errors:                            0
  checksum errors:                         0
  seqread iops:                            0
  seqwrite iops:                           0
  randread iops:                           0
  randwrite iops:                          0
  Bucket size:                             512 KiB
  First bucket:                            0
  Buckets:                                 1907670
  Last mount:                              (never)
  Last superblock write:                   0
  State:                                   rw
  Data allowed:                            journal,btree,user
  Has data:                                (none)
  Btree allocated bitmap blocksize:        1.00 B
  Btree allocated bitmap:                  0000000000000000000000000000000000000000000000000000000000000000
  Durability:                              1
  Discard:                                 0
  Freespace initialized:                   0
```
The above command completes successfully and shell does not hang.

**Host device info**:
```
Device- Raspberry Pi 5 (8GB)
Kernel- Linux rpl 6.11.0-rc5-v8-16k+ #1 SMP PREEMPT Sun Sep  1 01:52:30 IST 2024 aarch64 GNU/Linux (Commit `2d4c91787e9025d480448c58f396cbaba525e7f2` from `https://github.com/raspberrypi/linux/tree/rpi-6.11.y`)
bcachefs-tools binary version- 1.12.0 (Commit `b422b19f636329e1a082bcacd3ac6b485d7a5b3e` from master `https://github.com/koverstreet/bcachefs-tools` because 1.12.0 is not in releases yet)
```

**Comment by hb-lee** [comment]
How about doing the same operations again? I also encountered this issue, but when I switched back to the old version of bcachefs-tools and then to the new version, the problem disappeared again.

**Comment by hb-lee** [comment]
`
./bcachefs format /dev/loop1 

External UUID:                             c1df8d64-88ae-44cf-86f1-7ceb6b57b335
Internal UUID:                             1fdad45b-3cb8-4c05-9206-9696e9904c26
Magic number:                              c68573f6-66ce-90a9-d96a-60cf803df7ef
Device index:                              0
Label:                                     (none)
Version:                                   1.13: (unknown version)
Version upgrade complete:                  0.0: (unknown version)
Oldest version on disk:                    1.13: (unknown version)
Created:                                   Tue Sep 10 19:08:53 2024
Sequence number:                           0
Time of last write:                        Thu Jan  1 08:00:00 1970
Superblock size:                           976 B/1.00 MiB
Clean:                                     0
Devices:                                   1
Sections:                                  members_v1,members_v2
Features:                                  
Compat features:                           

Options:
  block_size:                              512 B
  btree_node_size:                         256 KiB
  errors:                                  continue [fix_safe] panic ro 
  metadata_replicas:                       1
  data_replicas:                           1
  metadata_replicas_required:              1
  data_replicas_required:                  1
  encoded_extent_max:                      64.0 KiB
  metadata_checksum:                       none [crc32c] crc64 xxhash 
  data_checksum:                           none [crc32c] crc64 xxhash 
  compression:                             none
  background_compression:                  none
  str_hash:                                crc32c crc64 [siphash] 
  metadata_target:                         none
  foreground_target:                       none
  background_target:                       none
  promote_target:                          none
  erasure_code:                            0
  inodes_32bit:                            1
  shard_inode_numbers:                     1
  inodes_use_key_cache:                    1
  gc_reserve_percent:                      8
  gc_reserve_bytes:                        0 B
  root_reserve_percent:                    0
  wide_macs:                               0
  promote_whole_extents:                   1
  acl:                                     1
  usrquota:                                0
  grpquota:                                0
  prjquota:                                0
  journal_flush_delay:                     1000
  journal_flush_disabled:                  0
  journal_reclaim_delay:                   100
  journal_transaction_names:               1
  allocator_stuck_timeout:                 30
  version_upgrade:                         [compatible] incompatible none 
  nocow:                                   0

members_v2 (size 160):
Device:                                    0
  Label:                                   (none)
  UUID:                                    b2cb08cc-837d-452a-9779-9084cb6af0b0
  Size:                                    12.0 GiB
  read errors:                             0
  write errors:                            0
  checksum errors:                         0
  seqread iops:                            0
  seqwrite iops:                           0
  randread iops:                           0
  randwrite iops:                          0
  Bucket size:                             256 KiB
  First bucket:                            0
  Buckets:                                 49152
  Last mount:                              (never)
  Last superblock write:                   0
  State:                                   rw
  Data allowed:                            journal,btree,user
  Has data:                                (none)
  Btree allocated bitmap blocksize:        1.00 B
  Btree allocated bitmap:                  0000000000000000000000000000000000000000000000000000000000000000
  Durability:                              1
  Discard:                                 0
  Freespace initialized:                   0

`

and my bcachefs-tools version:

`
git log
commit 1e058db4b603f8992b781b4654b48221dd04407a (HEAD -> master)
Author: Kent Overstreet <kent.overstreet@linux.dev>
Date:   Sat Aug 31 21:34:15 2024 -0400

    cmd_dump: Open in noexcl mode
    
    no need to make it harder to dump than it needs to be
    
    Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>
`

**Comment by hb-lee** [comment]
I encountered the same issue. For encrypt case, if you do with the ./bcachefs format --encrypted --no_passphrase /dev/loop1; it is the same. The question may be happen when begin initializing the file system.

**Comment by nitinkmr333** [comment]
The issue persists on stable release of kernel 6.11. I don't think it is related to bcachefs-tools as newer bcachefs-tools binary work fine with older bcachefs version (1.11 disk_accounting_inum) but not after that.

**Comment by hb-lee** [comment]
> The issue persists on stable release of kernel 6.11. I don't think it is related to bcachefs-tools as newer bcachefs-tools binary work fine with older bcachefs version (1.11 disk_accounting_inum) but not after that.

Yeah, that's because if you use the newer bcachefs-tools and the older bcachefs version will not initialize new filesystemfile system.

**Comment by hb-lee** [comment]
- stack
```
[New Thread 0x7ffff78ee600 (LWP 16425)]
starting version 1.12: rebalance_work_acct_fix
initializing new filesystem
[New Thread 0x7ffff78e5600 (LWP 16426)]
going read-write
[New Thread 0x7ffff6200600 (LWP 16427)]

bt
^C
Thread 1 "bcachefs" received signal SIGINT, Interrupt.
0x00007ffff7a88010 in ?? () from /usr/lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install keyutils-libs-1.6.3-4.oe2203sp2.x86_64 libaio-0.3.113-9.oe2203sp2.x86_64 libblkid-2.37.2-20.oe2203sp2.x86_64 libgcc-10.3.1-37.oe2203sp2.x86_64 libsodium-1.0.18-1.oe2203sp2.x86_64 libuuid-2.37.2-20.oe2203sp2.x86_64 lz4-1.9.3-3.oe2203sp2.x86_64 systemd-libs-249-52.oe2203sp2.x86_64 userspace-rcu-0.13.0-5.oe2203sp2.x86_64 zlib-1.2.11-22.oe2203sp2.x86_64 zstd-1.5.0-4.oe2203sp2.x86_64
(gdb) bt
#0  0x00007ffff7a88010 in ?? () from /usr/lib64/libc.so.6
#1  0x00007ffff7a8e2f2 in pthread_mutex_lock () from /usr/lib64/libc.so.6
#2  0x00005555556ccca2 in raw_spin_lock (lock=0x5555559aedc8) at include/linux/spinlock_types.h:25
#3  rcu_pending_rcu_cb (rcu=0x5555559aeed8) at libbcachefs/rcu_pending.c:308
#4  0x00005555556cd254 in call_srcu (func=0x5555556ccc70 <rcu_pending_rcu_cb>, rhp=0x5555559aeed8, ssp=<optimized out>) at include/linux/srcu.h:61
#5  __call_rcu (func=0x5555556ccc70 <rcu_pending_rcu_cb>, rhp=0x5555559aeed8, ssp=<optimized out>) at libbcachefs/rcu_pending.c:60
#6  __rcu_pending_enqueue (may_sleep=<optimized out>, ptr=0x0, head=0x555555ac4a40, head@entry=0x5555559aeed0, pending=0x7ffff7cbc9b0)
    at libbcachefs/rcu_pending.c:481
#7  rcu_pending_enqueue (pending=0x7ffff7cbc9b0, obj=obj@entry=0x555555ac4a40) at libbcachefs/rcu_pending.c:515
#8  0x0000555555604b13 in bkey_cached_free (bc=bc@entry=0x7ffff7cbc8e0, ck=ck@entry=0x555555ac4980) at libbcachefs/btree_key_cache.c:115
#9  0x0000555555606dd1 in bch2_btree_key_cache_drop (trans=trans@entry=0x555555ac6000, path=0x555555ac61f8) at libbcachefs/btree_key_cache.c:586
#10 0x000055555560f326 in bch2_trans_commit_write_locked (trace_ip=<optimized out>, stopped_at=<synthetic pointer>, flags=<optimized out>, trans=0x555555ac6000)
    at libbcachefs/btree_trans_commit.c:786
#11 do_bch2_trans_commit (trace_ip=<optimized out>, stopped_at=<synthetic pointer>, flags=<optimized out>, trans=0x555555ac6000)
    at libbcachefs/btree_trans_commit.c:861
#12 __bch2_trans_commit (trans=trans@entry=0x555555ac6000, flags=flags@entry=0) at libbcachefs/btree_trans_commit.c:1116
#13 0x0000555555623f53 in bch2_trans_commit (flags=0, journal_seq=0x0, disk_res=0x0, trans=0x555555ac6000) at libbcachefs/btree_update.h:184
#14 bch2_trans_mark_metadata_bucket (flags=<optimized out>, sectors=512, type=BCH_DATA_sb, b=0, ca=0x5555559d5800, trans=0x555555ac6000)
    at libbcachefs/buckets.c:1046
#15 bch2_trans_mark_metadata_bucket (trans=0x555555ac6000, ca=0x5555559d5800, b=0, type=BCH_DATA_sb, sectors=512, flags=<optimized out>)
    at libbcachefs/buckets.c:1028
#16 0x0000555555624411 in bch2_trans_mark_metadata_sectors (trans=trans@entry=0x555555ac6000, ca=ca@entry=0x5555559d5800, start=512, start@entry=8, 
    end=end@entry=2056, bucket=bucket@entry=0x7fffffffd078, bucket_sectors=bucket_sectors@entry=0x7fffffffd074, flags=BTREE_TRIGGER_transactional, type=BCH_DATA_sb)
    at libbcachefs/buckets.c:1063
#17 0x0000555555624516 in __bch2_trans_mark_dev_sb (trans=trans@entry=0x555555ac6000, ca=ca@entry=0x5555559d5800, flags=flags@entry=BTREE_TRIGGER_transactional)
    at libbcachefs/buckets.c:1103
#18 0x0000555555624637 in bch2_trans_mark_dev_sb (c=c@entry=0x7ffff7cb9000, ca=ca@entry=0x5555559d5800, flags=flags@entry=BTREE_TRIGGER_transactional)
    at libbcachefs/buckets.c:1131
#19 0x0000555555624853 in bch2_trans_mark_dev_sbs_flags (c=c@entry=0x7ffff7cb9000, flags=flags@entry=BTREE_TRIGGER_transactional) at libbcachefs/buckets.c:1141
#20 0x000055555562495a in bch2_trans_mark_dev_sbs (c=c@entry=0x7ffff7cb9000) at libbcachefs/buckets.c:1153
#21 0x0000555555692ea0 in bch2_fs_initialize (c=c@entry=0x7ffff7cb9000) at libbcachefs/recovery.c:1053
#22 0x00005555556b4ca1 in bch2_fs_start (c=c@entry=0x7ffff7cb9000) at libbcachefs/super.c:1038
#23 0x00005555556b830f in bch2_fs_open (devices=<optimized out>, nr_devices=<optimized out>, opts=...) at libbcachefs/super.c:2071
#24 0x00005555555b5c3e in cmd_format (argc=<optimized out>, argv=<optimized out>) at c_src/cmd_format.c:314
#25 0x00005555555aea3e in bcachefs::main ()
#26 0x00005555555ace83 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#27 0x00005555555b0f39 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hf61026c58232389e ()
#28 0x00005555557653dd in core::ops::function::impls::{impl#2}::call_once<(), (dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> () at library/core/src/ops/function.rs:284

```

**Comment by hb-lee** [comment]
Kent has solved this issue, pull the latest bcachefs-tools, and it won't appear anymore. Here is my test:

```
./bcachefs format /dev/loop1 
External UUID:                             aca077f4-7acd-4975-beb4-b16677d1c8cb
Internal UUID:                             56da90fe-0ea5-453b-8884-598592c88b83
Magic number:                              c68573f6-66ce-90a9-d96a-60cf803df7ef
Device index:                              0
Label:                                     (none)
Version:                                   1.12: rebalance_work_acct_fix
Version upgrade complete:                  0.0: (unknown version)
Oldest version on disk:                    1.12: rebalance_work_acct_fix
Created:                                   Mon Sep 30 10:31:39 2024
Sequence number:                           0
Time of last write:                        Thu Jan  1 08:00:00 1970
Superblock size:                           976 B/1.00 MiB
Clean:                                     0
Devices:                                   1
Sections:                                  members_v1,members_v2
Features:                                  new_siphash,new_extent_overwrite,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                           

Options:
  block_size:                              512 B
  btree_node_size:                         256 KiB
  errors:                                  continue [fix_safe] panic ro 
  metadata_replicas:                       1
  data_replicas:                           1
  metadata_replicas_required:              1
  data_replicas_required:                  1
  encoded_extent_max:                      64.0 KiB
  metadata_checksum:                       none [crc32c] crc64 xxhash 
  data_checksum:                           none [crc32c] crc64 xxhash 
  compression:                             none
  background_compression:                  none
  str_hash:                                crc32c crc64 [siphash] 
  metadata_target:                         none
  foreground_target:                       none
  background_target:                       none
  promote_target:                          none
  erasure_code:                            0
  inodes_32bit:                            1
  shard_inode_numbers:                     1
  inodes_use_key_cache:                    1
  gc_reserve_percent:                      8
  gc_reserve_bytes:                        0 B
  root_reserve_percent:                    0
  wide_macs:                               0
  promote_whole_extents:                   1
  acl:                                     1
  usrquota:                                0
  grpquota:                                0
  prjquota:                                0
  journal_flush_delay:                     1000
  journal_flush_disabled:                  0
  journal_reclaim_delay:                   100
  journal_transaction_names:               1
  allocator_stuck_timeout:                 30
  version_upgrade:                         [compatible] incompatible none 
  nocow:                                   0

members_v2 (size 160):
Device:                                    0
  Label:                                   (none)
  UUID:                                    4b858cbc-d6e9-40aa-b49c-194e2f662f1f
  Size:                                    12.0 GiB
  read errors:                             0
  write errors:                            0
  checksum errors:                         0
  seqread iops:                            0
  seqwrite iops:                           0
  randread iops:                           0
  randwrite iops:                          0
  Bucket size:                             256 KiB
  First bucket:                            0
  Buckets:                                 49152
  Last mount:                              (never)
  Last superblock write:                   0
  State:                                   rw
  Data allowed:                            journal,btree,user
  Has data:                                (none)
  Btree allocated bitmap blocksize:        1.00 B
  Btree allocated bitmap:                  0000000000000000000000000000000000000000000000000000000000000000
  Durability:                              1
  Discard:                                 0
  Freespace initialized:                   0
starting version 1.12: rebalance_work_acct_fix
initializing new filesystem
going read-write
initializing freespace
shutdown complete, journal seq 8

```

**Comment by koverstreet** [comment]
I just pulled the fix for this into -tools.
