### ISSUE TITLE
After removing a device, `fs usage` segfaults

### ISSUE THREAD

**Issue by vitrvvivs** [koverstreet/bcachefs#86]
Running on `Linux 5.3.18-1-bcachefs-git-196125-g5cc7cce89a66 #1 SMP PREEMPT Thu, 26 Dec 2019 00:59:34 +0000 x86_64 GNU/Linux` ; `bcachefs tool version v0.1-167-gc07ac50`

```
# bcachefs fs usage -h /mnt
Filesystem 2a4e174b-d84c-46f8-a536-3650e37a0ed3:
Size:                      26.8T
Used:                       2.1T
Online reserved:               0 

Data type       Required/total  Devices
Segmentation fault (core dumped)
```

```
#0  0x00007f5f0b344e1b in __strcpy_avx2 () from /usr/lib/libc.so.6
#1  0x00005593db403438 in print_fs_usage (path=0x7ffd035a3d4c "/mnt",
units=HUMAN_READABLE) at cmd_fs.c:112
#2  0x00005593db4037e5 in cmd_fs_usage (argc=0, argv=0x7ffd035a1e20) at cmd_fs.c:160
#3  0x00005593db308898 in fs_cmds (argc=3, argv=0x7ffd035a1e08) at bcachefs.c:106
#4  0x00005593db308bb4 in main (argc=4, argv=0x7ffd035a1e08) at bcachefs.c:178
```
I removed devices 0-3 (the cache) for testing. Even after remounting, the remaining devices were still indexed 4-7.

Adding the old devices back fixed it.

**Comment by koverstreet** [comment]
Should be fixed by 7c39a1cf1b
