### ISSUE TITLE
fsck throws segfault

### ISSUE THREAD

**Issue by marcin-github** [koverstreet/bcachefs#95]
```
# echo "bt full" | gdb -q /sbin/bcachefs 'core-1585556564-0-11-!sbin!bcachefs-21346'
Reading symbols from /sbin/bcachefs...
Reading symbols from /usr/lib64/debug//sbin/bcachefs.debug...
[New LWP 21346]
[New LWP 21349]
[New LWP 21347]
[New LWP 21356]
[New LWP 21350]
[New LWP 21351]
[New LWP 21470]
[New LWP 21409]
[New LWP 21355]
[New LWP 21348]
[New LWP 21353]
[New LWP 21354]
[New LWP 21352]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `bcachefs fsck -yv /dev/vg-ogolny/dane2'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  bch2_disk_reservation_add (c=0x55f9077d2000, res=0x0, sectors=14, flags=<optimized out>) at libbcachefs/buckets.c:1918
1918                    res->sectors                    += sectors;
[Current thread is 1 (Thread 0x7f100d681b80 (LWP 21346))]
(gdb) #0  bch2_disk_reservation_add (c=0x55f9077d2000, res=0x0, sectors=14, flags=<optimized out>) at libbcachefs/buckets.c:1918
        pcpu = <optimized out>
        old = <optimized out>
        v = <optimized out>                                                                                                                                                                                           get = <optimized out>
        sectors_available = <error reading variable sectors_available (That operation is not available on integers of more than 8 bytes.)>
        ret = <optimized out>
#1  0x000055f905b746bf in bch2_extent_can_insert (trans=trans@entry=0x7fff8c3773f0, iter=<optimized out>, insert=0x7f1008017090) at libbcachefs/extent_update.c:202
        flags = <optimized out>
        l = <optimized out>
        node_iter = {data = {{k = 725, end = 5031}, {k = 0, end = 0}, {k = 0, end = 0}}}
        _k = 0x7f0ffc0056b0
        k = {k = 0x7fff8c377270, v = <optimized out>}
        unpacked = {u64s = 7 '\a', format = 1 '\001', needs_whiteout = 1 '\001', type = 6 '\006', pad = "", version = {lo = 0, hi = 0}, size = 15, p = {snapshot = 0, offset = 1255, inode = 4251}}
        sectors = <optimized out>
        __PRETTY_FUNCTION__ = "bch2_extent_can_insert"
#2  0x000055f905b76b45 in btree_key_can_insert (u64s=<synthetic pointer>, insert=<optimized out>, iter=<optimized out>, trans=0x7fff8c3773f0) at libbcachefs/btree_iter.h:136
        c = <optimized out>
        b = <optimized out>
        c = <optimized out>
        b = <optimized out>
        ret = <optimized out>
#3  bch2_trans_commit_write_locked (stopped_at=<synthetic pointer>, trans=0x7fff8c3773f0) at libbcachefs/btree_update_leaf.c:386
        c = 0x55f9077d2000
        i = <optimized out>
        u64s = <optimized out>
        marking = <optimized out>
        ret = <optimized out>
        fs_usage = 0x0
        c = <optimized out>
        fs_usage = <optimized out>
        i = <optimized out>
        u64s = <optimized out>
        marking = <optimized out>
        ret = <optimized out>
        __var = <optimized out>
#4  do_bch2_trans_commit (stopped_at=<synthetic pointer>, trans=0x7fff8c3773f0) at libbcachefs/btree_update_leaf.c:503
        i = <optimized out>
        iter = <optimized out>
        ret = <optimized out>
        i = <optimized out>
        iter = <optimized out>
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "do_bch2_trans_commit"
#5  __bch2_trans_commit (trans=trans@entry=0x7fff8c3773f0) at libbcachefs/btree_update_leaf.c:888
        i = <optimized out>
        iter = <optimized out>
        trans_trigger_run = <optimized out>
        u64s = <optimized out>
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "__bch2_trans_commit"
#6  0x000055f905b88aa5 in bch2_trans_commit (flags=74, journal_seq=0x0, disk_res=0x0, trans=0x7fff8c3773f0) at libbcachefs/btree_update.h:98
No locals.
#7  bch2_journal_replay_key (c=c@entry=0x55f9077d2000, id=BTREE_ID_EXTENTS, level=0, k=0x7f1008017090) at libbcachefs/recovery.c:436
        _ret = <optimized out>
        trans = {c = 0x55f9077d2000, ip = 94528031197519, iters_linked = 1, iters_live = 0, iters_touched = 1, nr_iters = 1 '\001', nr_updates = 1 '\001', nr_updates2 = 1 '\001', size = 64 '@',
          used_mempool = 0, error = 0, nounlock = 0, need_reset = 0, mem_top = 0, mem_bytes = 0, mem = 0x0, iters = 0x55f907c38000, updates = 0x55f907c3b000, updates2 = 0x55f907c3b600, journal_res = {
            ref = false, idx = 0 '\000', u64s = 0, offset = 0, seq = 0}, journal_preres = {u64s = 0}, journal_seq = 0x0, disk_res = 0x0, flags = 74, journal_u64s = 6, journal_preres_u64s = 0,
fs_usage_delta--Type <RET> for more, q to quit, c to continue without paging--          s = 0x0, iters_onstack = {{trans = 0x7fff8c377640, pos = {snapshot = 125869640, offset = 12884923897, inode = 10103672
657011539968}, pos_after_commit = {snapshot = 32767,
                offset = 10336953745800840704, inode = 140735545832832}, flags = 3, idx = 0 '\000', btree_id = BTREE_ID_EXTENTS, uptodate = BTREE_ITER_UPTODATE, level = 0, min_depth = 0, locks_want = 0,
              nodes_locked = 0, nodes_intent_locked = 0, l = {{b = 0x3, iter = {data = {{k = 40520, end = 1920}, {k = 22009, end = 0}, {k = 24956, end = 90}}}, lock_seq = 0}, {b = 0x7fff8c377640, iter = {
                    data = {{k = 36160, end = 1464}, {k = 22009, end = 0}, {k = 24977, end = 3468}}}, lock_seq = 32528}, {b = 0x18, iter = {data = {{k = 36160, end = 1464}, {k = 22009, end = 0}, {
                        k = 30112, end = 35895}}}, lock_seq = 32767}, {b = 0x7fff8c377640, iter = {data = {{k = 40448, end = 1920}, {k = 22009, end = 0}, {k = 6, end = 0}}}, lock_seq = 0}}, k = {
                u64s = 0 '\000', format = 38 '&', needs_whiteout = 1 '\001', type = 132 '\204', pad = "", version = {lo = 1016201631739412480, hi = 2406759594}, size = 0, p = {snapshot = 32767,
                  offset = 0, inode = 140735545833120}}}, {trans = 0x0, pos = {snapshot = 5923196, offset = 1016201631739412480, inode = 412234674328583338}, pos_after_commit = {snapshot = 22009,
                offset = 139706923508914, inode = 0}, flags = 28760, idx = 1 '\001', btree_id = BTREE_ID_NR, uptodate = BTREE_ITER_UPTODATE, level = 0, min_depth = 1, locks_want = 15, nodes_locked = 7,
              nodes_intent_locked = 0, l = {{b = 0x100000000, iter = {data = {{k = 0, end = 0}, {k = 0, end = 0}, {k = 28816, end = 2049}}}, lock_seq = 32528}, {b = 0x800000000, iter = {data = {{k = 0,
                        end = 0}, {k = 0, end = 0}, {k = 28856, end = 2049}}}, lock_seq = 32528}, {b = 0xd00000000, iter = {data = {{k = 50054, end = 3472}, {k = 32528, end = 0}, {k = 0, end = 0}}},
                  lock_seq = 0}, {b = 0x8f743caa0e1a4600, iter = {data = {{k = 16716, end = 5}, {k = 0, end = 0}, {k = 24, end = 0}}}, lock_seq = 0}}, k = {u64s = 192 '\300', format = 5 '\005',
                needs_whiteout = 1 '\001', type = 165 '\245', pad = "\r", version = {lo = 414528940372164368, hi = 22009}, size = 228934080, p = {snapshot = 32528, offset = 0, inode = 94528060858368}}}},
          updates_onstack = {{trigger_flags = 227599576, trans_triggers_run = 0, k = 0x2f31203a61746164, iter = 0x0}, {trigger_flags = 10, trans_triggers_run = 0, k = 0x6, iter = 0x55f907809e00}},
          updates2_onstack = {{trigger_flags = 23, trans_triggers_run = 0, k = 0x18, iter = 0x2}, {trigger_flags = 95980864, trans_triggers_run = 1, k = 0x0, iter = 0x7fff8c377570}}}
        _ret = <optimized out>
        _ret2 = <optimized out>
#8  0x000055f905b8a96e in bch2_journal_replay (keys=..., c=0x55f9077d2000) at libbcachefs/recovery.c:466
        j = 0x55f9077db4c0
        i = 0x55f907809e18
        ret = <optimized out>
        j = <optimized out>
        i = <optimized out>
        ret = <optimized out>
#9  bch2_fs_recovery (c=0x55f9077d2000) at libbcachefs/recovery.c:959
        err = 0x55f905c0b2fe "journal replay failed"
        clean = <optimized out>
        journal_seq = <optimized out>
        wrote = false
        write_sb = false
        ret = <optimized out>
#10 0x000055f905bab47d in bch2_fs_start (c=c@entry=0x55f9077d2000) at include/linux/percpu-refcount.h:140
        err = 0x55f905c072c0 "cannot allocate memory"
        mi = <optimized out>
        ca = <optimized out>
        now = <optimized out>
        i = 1
        ret = -22
        __PRETTY_FUNCTION__ = "bch2_fs_start"
#11 0x000055f905bad495 in bch2_fs_open (devices=devices@entry=0x7fff8c377a28, nr_devices=nr_devices@entry=1, opts=...) at libbcachefs/super.c:1877
        sb = 0x55f9077c7fc0
        c = 0x55f9077d2000
        i = 1
        best_sb = <optimized out>
        err = 0x55f905c0f997 "insufficient devices"
        ret = -12
        __func__ = "bch2_fs_open"
#12 0x000055f905b48990 in cmd_fsck (argc=1, argv=0x7fff8c377a28) at cmd_fsck.c:70
        opts = {block_size_defined = 0, btree_node_size_defined = 0, errors_defined = 0, metadata_replicas_defined = 0, data_replicas_defined = 0, metadata_replicas_required_defined = 0,
          data_replicas_required_defined = 0, metadata_checksum_defined = 0, data_checksum_defined = 0, compression_defined = 0, background_compression_defined = 0, str_hash_defined = 0,
          foreground_target_defined = 0, background_target_defined = 0, promote_target_defined = 0, erasure_code_defined = 0, inodes_32bit_defined = 0, gc_reserve_percent_defined = 0,
          gc_reserve_bytes_defined = 0, root_reserve_percent_defined = 0, wide_macs_defined = 0, inline_data_defined = 0, acl_defined = 0, usrquota_defined = 0, grpquota_defined = 0, prjquota_defined = 0,
          degraded_defined = 1, discard_defined = 0, verbose_defined = 1, journal_flush_disabled_defined = 0, fsck_defined = 1, fix_errors_defined = 1, ratelimit_errors_defined = 0, nochanges_defined = 0,
          norecovery_defined = 0, keep_journal_defined = 0, noexcl_defined = 0, sb_defined = 0, read_only_defined = 0, nostart_defined = 0, reconstruct_alloc_defined = 0, version_upgrade_defined = 0,
          project_defined = 0, fs_size_defined = 0, bucket_defined = 0, durability_defined = 0, block_size = 0, btree_node_size = 0, errors = 0 '\000', metadata_replicas = 0 '\000',
          data_replicas = 0 '\000', metadata_replicas_required = 0 '\000', data_replicas_required = 0 '\000', metadata_checksum = 0 '\000', data_checksum = 0 '\000', compression = 0 '\000',
          background_compression = 0 '\000', str_hash = 0 '\000', foreground_target = 0, background_target = 0, promote_target = 0, erasure_code = 0, inodes_32bit = 0 '\000',
          gc_reserve_percent = 0 '\000', gc_reserve_bytes = 0, root_reserve_percent = 0 '\000', wide_macs = 0 '\000', inline_data = 0 '\000', acl = 0 '\000', usrquota = 0 '\000', grpquota = 0 '\000',
          prjquota = 0 '\000', degraded = 1 '\001', discard = 0 '\000', verbose = 1 '\001', journal_flush_disabled = 0 '\000', fsck = 1 '\001', fix_errors = 1 '\001', ratelimit_errors = 0 '\000',
nochanges --Type <RET> for more, q to quit, c to continue without paging--          = 0 '\000', norecovery = 0 '\000', keep_journal = 0 '\000', noexcl = 0 '\000', sb = 0, read_only = 0 '\000', nostart = 0 '
\000', reconstruct_alloc = 0 '\000',
          version_upgrade = 0 '\000', project = 0 '\000', fs_size = 0, bucket = 0, durability = 0 '\000'}
        i = <optimized out>
        opt = <optimized out>
        ret = 0
        c = <optimized out>
#13 0x000055f905b44f5e in main (argc=<optimized out>, argv=0x7fff8c377a18) at bcachefs.c:165
        cmd = <optimized out>
DW_FORM_strp pointing outside of .debug_str section [in module /usr/lib64/debug/lib64/libc-2.29.so.debug]
(gdb) quit
```
 at rev 2aed686c235a7d08adf601

**Comment by marcin-github** [comment]
I have this issue on two fs.

**Comment by marcin-github** [comment]
Fixed with latest commits. Thank you.
